### ISSUE TITLE
Can't get erigon started properly on bsc mainnet

### ISSUE THREAD

**Issue by ZiyuanStar** [node-real/bsc-erigon#10]
#### System information

Erigon version: `./erigon --version`
erigon version 2.40.0-dev-3da15fcb

OS & Version: Linux

Erigon Command (with flags/config):
nohup ./build/bin/erigon --chain bsc --db.pagesize=16k --datadir=/server/bsc-erigon/data --http --ws --http.api=eth,debug,net,trace,web3,erigon --log.dir.path=/server/bsc-erigon/logs

Chain/Network: BSC

#### Expected behaviour
Start importing new blocks after downloading snapshot completes

#### Actual behaviour
Stuck at stat and goes nowhere, keep receiving error message:
keeps logging message like this: t=2023-03-31T03:19:08+0000 lvl=dbug msg="[p2p] Handshake failure" peer=c3276083eebc96a44003 err="network id does not match: theirs 1971, ours 56"
Tried adding --staticpeers flag but doesn’t work. 

#### Steps to reproduce the behaviour
Just start erigon using above command, you will see the issue.

#### Backtrace

````
[backtrace]
````

**Comment by ZiyuanStar** [comment]
<img width="1292" alt="图片" src="https://user-images.githubusercontent.com/94595924/229021389-01a70935-5abf-467f-8626-d8c597487551.png">

**Comment by ZiyuanStar** [comment]
console log:
<img width="1229" alt="图片" src="https://user-images.githubusercontent.com/94595924/229336939-55b87610-4cd1-41e8-b424-2a4d146ea53e.png">

erigon-user.log:
<img width="1160" alt="图片" src="https://user-images.githubusercontent.com/94595924/229336974-1dc49a01-10dc-4711-b433-ffbddd00b9be.png">

**Comment by ZiyuanStar** [comment]
snapshot was downloaded from: https://github.com/bnb-chain/bsc-snapshots#endpoint-1

**Comment by blxdyx** [comment]
The console log seems normal.
