### ISSUE TITLE
RPC: trace filter handler crush

### ISSUE THREAD

**Issue by mateipopp** [node-real/bsc-erigon#106]
#### System information

Erigon version: `./erigon --version`

OS & Version: Windows/Linux/OSX
ubuntu 22.04

Chain/Network: 
BSC Mainnet

#### Expected behaviour

Returns errors on trace_filter method

#### Backtrace

````
{"id":45656173,"jsonrpc":"2.0","method":"trace_filter","params":[{"fromBlock":"0x1b47446","toAddress":["0xf584a17df21afd9de84f47842eceaf6042b1bb5b"],"toBlock":"0x1b47446"}]}
"error":{"message":"method handler crashed","code":-32000}
````
This issue was fixed by the erigon team:
https://github.com/ledgerwatch/erigon/pull/7539/files

**Comment by quick-pawiromitchel** [comment]
Noticed a similar issue
'{"method":"trace_filter","params":[{"fromBlock":"0x1B5C0D9","toBlock":"0x1B5C0D9"}],"id":1,"jsonrpc":"2.0"}'

On `erigon/2.43.0/linux-amd64/go1.20.4` BSC Mainnet as well

# Stacktrace
```
May 31 10:30:02 erigon[5395]: [EROR] [05-31|10:30:02.588] RPC method trace_filter crashed: runtime error: invalid memory address or nil pointer dereference
May 31 10:30:02 erigon[5395]: [service.go:217 panic.go:884 panic.go:260 signal_unix.go:837 stream.go:184 trace_filtering.go:384 value.go:586 value.go:370 service.go:222 handler.go:494 handler.go:444 handler.go:392 handler.go:223 handler.go:316 asm_amd64.s:1598]
May 31 10:30:02 erigon[5395]: [WARN] [05-31|10:30:02.588] Served conn=xxx.xxx.xxx.xxx:60594 method=trace_filter reqid=1 t=173.651µs err="method handler crashed"
```

**Comment by quickchase** [comment]
Disregard the above, patching and building off the correct commit resolved my issues.
