### ISSUE TITLE
Please change version numbers for fork

### ISSUE THREAD

**Issue by PeaStew** [node-real/bsc-erigon#11]
If possible it would be great if the version numbers when queried could the could be changed to reflect that it is a fork, this would make it much easier for version tracking vs your repo.

It could still have reference to the base Erigon version  but could also reflect the version number in the repo, something like:

bsc-erigon 1.0.2 upstream version 2.40.0-dev-3da15fcb maybe

**Comment by blxdyx** [comment]
Is it ok for you to add the version information in the release notes?
