### ISSUE TITLE
node falls behind multiple times per day with "No block headers to write in this log period"

### ISSUE THREAD

**Issue by densone** [node-real/bsc-erigon#113]
#### System information

Erigon version: `1.0.9 from releases page. Also happens on previous releases. `

OS & Version:  Linux

Erigon Command (with flags/config):

I've tried many variations but this is what I am running right now. 
```
erigon --sentry.drop-useless-peers --p2p.protocol=66 --txpool.disable --metrics.addr=0.0.0.0 --db.pagesize=16k --datadir /blockjoy/bsc --private.api.addr=localhost:9090 --chain=bsc --metrics --log.dir.path /blockjoy/bsc --metrics --maxpeers=1000 --http.vhosts https:/xxxx.slc.blockjoy.com,localhost --snap.stop true --snapshots false
```

Concensus Layer:

none 

Chain/Network:  BSC Mainnet

#### Expected behaviour

Block sync normally 

#### Actual behaviour
Node will sync normally then multiple times per day it will get stuck on the following message

**No block headers to write in this log period block**

#### Steps to reproduce the behaviour

It happens all the time, multiple times per day.  It's a full archive node. Data downloaded from BSC snapshots. 
````


Any help would be very much appreciated.

**Comment by setunapo** [comment]
seems occurs occasionally, sometime restart could solve the issue.
have you tried restart the node?

**Comment by densone** [comment]
restart fixes it, but it's not optimal, so the best thing to do is just synchronized restart?

**Comment by fylsan3** [comment]
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"admin_peers","params":[],"id":1}' http://x.x.x.x:8545| jq -c '.result[].enode' |wc -l
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  381k    0  381k  100    59  9084k   1404 --:--:-- --:--:-- --:--:-- 9085k
664
我现在连接了664个对等节点也会出现这种问题。实际上它大约在几十分钟内自己会恢复，但是当我运行一周后再出在这种问题就需要重启了，不然高度会卡住。
我也使用了--sentry.drop-useless-peers true  我觉得现在所连接的节点中还是有坏的节点避开了检测在我的列表里保留着当我的列表里都是坏节点的时候就会出现 ”No block headers to write in this log period“

**Comment by fylsan3** [comment]
> #### 系统信息
> 埃里贡版本：`1.0.9 from releases page. Also happens on previous releases. `
> 
> 操作系统和版本：Linux
> 
> Erigon 命令（带有标志/配置）：
> 
> 我尝试了很多变体，但这就是我现在正在运行的。
> 
> ```
> erigon --sentry.drop-useless-peers --p2p.protocol=66 --txpool.disable --metrics.addr=0.0.0.0 --db.pagesize=16k --datadir /blockjoy/bsc --private.api.addr=localhost:9090 --chain=bsc --metrics --log.dir.path /blockjoy/bsc --metrics --maxpeers=1000 --http.vhosts https:/xxxx.slc.blockjoy.com,localhost --snap.stop true --snapshots false
> ```
> 
> 共识层：
> 
> 没有任何
> 
> 链/网络：BSC 主网
> 
> #### 预期行为
> 块同步正常
> 
> #### 实际行为
> 节点将正常同步然后每天多次它会卡在以下消息上
> 
> **没有要写入此日志周期块的块头**
> 
> #### 重现该行为的步骤
> 它一直在发生，每天发生多次。这是一个完整的存档节点。从 BSC 快照下载的数据。
> 
> ```
> 
> 
> Any help would be very much appreciated.  
> ```

我遇到了你这种问题，删除了--p2p.protocol=66 效果还可以   你可以试一下

**Comment by quickchase** [comment]
I run all nodes with p2p 66 and drop useless peers, still happens all the time

**Comment by densone** [comment]
I ended up writing a shell script to track and restart ..  works for now but not great long term

**Comment by icculp** [comment]
```[INFO] [06-04|16:13:40.775] [2/15 Headers] No block headers to write in this log period block number=28805640
[INFO] [06-04|16:13:40.775] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=13 skelMin=28805639 skelMax=28805831 resp=706 respMin=28805639 respMax=28811348 dups=127141
[INFO] [06-04|16:14:00.775] [2/15 Headers] No block headers to write in this log period block number=28805640
[INFO] [06-04|16:14:00.775] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=13 skelMin=28805639 skelMax=28805831 resp=693 respMin=28597700 respMax=28811354 dups=127123
[INFO] [06-04|16:14:20.775] [2/15 Headers] No block headers to write in this log period block number=28805640
[INFO] [06-04|16:14:20.775] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=28805639 skelMax=28805831 resp=743 respMin=28690838 respMax=28811361 dups=136723
[INFO] [06-04|16:14:40.775] [2/15 Headers] No block headers to write in this log period block number=28805640
[INFO] [06-04|16:14:40.775] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=13 skelMin=28805639 skelMax=28805831 resp=685 respMin=28085190 respMax=28811367 dups=126735
[INFO] [06-04|16:15:00.774] [2/15 Headers] No block headers to write in this log period block number=28805640
[INFO] [06-04|16:15:00.775] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=28805639 skelMax=28805831 resp=696 respMin=28690838 respMax=28811374 dups=129420
[INFO] [06-04|16:15:20.775] [2/15 Headers] No block headers to write in this log period block number=28805640
[INFO] [06-04|16:15:20.775] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=28805639 skelMax=28805831 resp=779 respMin=28805639 respMax=28811381 dups=144212
[INFO] [06-04|16:15:33.113] [p2p] GoodPeers                          eth66=829
[INFO] [06-04|16:15:40.775] [2/15 Headers] No block headers to write in this log period block number=28805640
[INFO] [06-04|16:15:40.775] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=12 skelMin=28805639 skelMax=28805831 resp=631 respMin=28085190 respMax=28811387 dups=117896
[INFO] [06-04|16:16:00.775] [2/15 Headers] No block headers to write in this log period block number=28805640
[INFO] [06-04|16:16:00.775] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=28805639 skelMax=28805831 resp=701 respMin=28085190 respMax=28811394 dups=130000
[INFO] [06-04|16:16:20.775] [2/15 Headers] No block headers to write in this log period block number=28805640
[INFO] [06-04|16:16:20.775] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=28805639 skelMax=28805831 resp=758 respMin=28068508 respMax=28811401 dups=140559
[INFO] [06-04|16:16:40.775] [2/15 Headers] No block headers to write in this log period block number=28805640
[INFO] [06-04|16:16:40.775] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=13 skelMin=28805639 skelMax=28805831 resp=699 respMin=28805639 respMax=28811407 dups=130000
[INFO] [06-04|16:17:00.775] [2/15 Headers] No block headers to write in this log period block number=28805640
[INFO] [06-04|16:17:00.775] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=14 skelMin=28805639 skelMax=28805831 resp=740 respMin=28805639 respMax=28811414 dups=136725```

Just closed another issue cuz I thought it was running stable, but nope.

**Comment by calmbeing** [comment]
same issue as https://github.com/node-real/bsc-erigon/issues/104, merged and closed here
