### ISSUE TITLE
BSC Mainnet Archival falling out of sync, repeating stages 2 and 5

### ISSUE THREAD

**Issue by icculp** [node-real/bsc-erigon#117]
#### System information

Started on 1.08 and upgraded to 1.09, same

Debian 11

Erigon Command (with flags/config):
```"  --config=/erigon/config/config.toml   --torrent.upload.rate=\"512mb\" --torrent.download.rate=\"512mb\" --db.pagesize=16k  --maxpeers=1000 --p2p.protocol=66  --sentry.drop-useless-peers --downloader.verify  --staticpeers enode://0fe2af9a5e6fdaa1782eb1025d516984395197699bf677a78021fa6158660f88bcfe577bb5d05c7e1b5bf8ff5a6bf60d9174437c2268bec74cb16221e37ab075@52.210.159.54:30311,enode://ec23c796b2c27a9310645cd64140f15b8c9c7e3a30f7c3fc930ba56d4740018e6f37f463100714723330c3b63f894cdd63d69271c2135b66a4b0feae7832f895@52.69.9.248:30311,enode://1cc4534b14cfe351ab740a1418ab944a234ca2f702915eadb7e558a02010cb7c5a8c295a3b56bcefa7701c07752acd5539cb13df2aab8ae2d98934d712611443@100.24.179.110:30311,enode://e071da3e6d4ef916c25901e976da90cfc5ec7de3269de09719637787778824da3186638a0f94c03ad90cdafeab32263f6f6cd9b0fbed67a744c25d38f67a5b5e@54.65.247.12:30311,enode://45146a7cb02cd127d21cf3c37f533623c5caf4dea31aecc619d5e47ccc38f8377f08be8ce60f9c3429efaa50825c435498880a46b4634ccdc3ed8eb72ba054ae@3.209.235.131:30311,enode://f2d2d0056c593b0b8309b10c0a6ca776372d23d57481f58e1b3893f2846b2acd8440a6b2b2d0c63b9e63f38e5c4f3d44976a6e54bc770526be557d3666776d32@35.73.82.38:30311,enode://e7ea581db0d0d927e0b19d2089c5da3a8b2ca1888c1d4bbc47b7b8fff18ccd9a35091ce4432e251e117c392a8bd62ec68213082311fafd5753cd85a75dbf4792@52.209.117.192:30311,enode://590e3069563fa0c46f72b6724c028aa2dda8f4e9ca70b7f288b0c1dcf9d32d74ac98d05da5a3c6473f133b13ed98523c41a567e18e6eadc8b156a3a2b11a791c@3.212.19.242:30311,enode://c09132e0ac4875c1b0ac2856e032875f174debc76c779b125ec2dc44e94ae42b6db4412b970f15a6e618a48a6ffff6f42230222d6e61e30fd4426a1af82b154b@54.85.57.23:30311,enode://28b1d16562dac280dacaaf45d54516b85bc6c994252a9825c5cc4e080d3e53446d05f63ba495ea7d44d6c316b54cd92b245c5c328c37da24605c4a93a0d099c4@52.215.151.117:30311,enode://231491fb31dc6e22aed4533c8eac352e477349ebf8727a6531161f86ae1b59e2acfcf6412473c02b7e57a130e9dd572e3431892dfa18a171d59978c7906b405f@54.95.125.14:30311,enode://38144f02adbe8817b2b0f241f921491bc612dd8cd603fa9cd3faa31c76697ad5e00297cba38d0a8f594752c56c9a7e84f53d7f71c0b37b5680cea5e732b6b946@34.243.164.24:30311,enode://faf14b1c38422f9576760b4d86b62ee6d2b436d1cac9965adf3f5af23dece3a9829ad3f53015cda992c6bbdc44816ccc96043fa342b839308681909cbd0ea9b2@52.71.45.253:30311,enode://67f45bf2e2afe35b390fabffe5865038fe70911a0236e62870c73f06804362dd886354d1ff1f862d950c5e0b50e8a2d68b45be90c1c76ce98f7b87123fe05bcc@13.231.3.53:30311,enode://1cc4534b14cfe351ab740a1418ab944a234ca2f702915eadb7e558a02010cb7c5a8c295a3b56bcefa7701c07752acd5539cb13df2aab8ae2d98934d712611443@52.71.43.172:30311",```

Chain/Network: 
BSC Archival

#### Expected behaviour
Stays in sync

#### Actual behaviour
Falls behind, repeats stages 2 and 5

#### Steps to reproduce the behaviour
Command above, have also tried adding `--bodies.cache=21474836480   --batchSize=1024M  --etl.bufferSize=1024M` with same behavior

```[INFO] [06-02|02:58:37.317] [2/15 Headers] Waiting for headers...    from=28737914
[INFO] [06-02|02:58:37.623] [2/15 Headers] Processed                 highest inserted=28737967 age=0
[INFO] [06-02|02:58:37.642] [5/15 Bodies] Processing bodies...       from=28736695 to=28737967
[INFO] [06-02|02:58:57.642] [5/15 Bodies] No block bodies to write in this log period block number=28736695
[INFO] [06-02|02:59:01.596] [snapshots] Blocks Stat                  blocks=28645k indices=28645k alloc=4.7GB sys=10.3GB
[INFO] [06-02|02:59:09.332] [p2p] GoodPeers                          eth66=935
[INFO] [06-02|02:59:10.692] [txpool] stat                            pending=10000 baseFee=1 queued=29209 alloc=4.9GB sys=10.3GB
[INFO] [06-02|02:59:17.642] [5/15 Bodies] No block bodies to write in this log period block number=28736695
[INFO] [06-02|02:59:37.642] [5/15 Bodies] No block bodies to write in this log period block number=28736695
[INFO] [06-02|02:59:57.643] [5/15 Bodies] Downloading block bodies   block_num=28736695 delivery/sec=337.0KB wasted/sec=0B remaining=1271 delivered=158 cache=184.8MB alloc=6.0GB sys=10.3GB
[INFO] [06-02|03:00:10.669] [txpool] stat                            pending=10000 baseFee=1 queued=30000 alloc=6.4GB sys=10.3GB
[INFO] [06-02|03:00:17.642] [5/15 Bodies] No block bodies to write in this log period block number=28736695
[INFO] [06-02|03:00:17.643] [5/15 Bodies] DONE                       in=1m40.000590351s
[INFO] [06-02|03:00:17.653] Commit cycle                             in=9.273158ms
[INFO] [06-02|03:00:17.653] Timings (slower than 50ms)               Headers=305ms Bodies=1m40s
[INFO] [06-02|03:00:17.653] Tables                                   PlainState=241.7GB AccountChangeSet=557.4GB StorageChangeSet=1.3TB BlockTransaction=5.3GB TransactionLog=2.3TB FreeList=66.3MB ReclaimableSpace=265.1GB
[INFO] [06-02|03:00:17.656] RPC Daemon notified of new headers       from=28736943 to=28737967 hash=0xb432f4a7e340bd7cd50bca616a44d9fbb8e49b9257c40b41c1c203fb0478bb26 header sending=2.969216ms log sending=544ns
[INFO] [06-02|03:00:17.734] [2/15 Headers] Waiting for headers...    from=28737967
[INFO] [06-02|03:00:18.071] [2/15 Headers] Processed                 highest inserted=28738000 age=2s
[INFO] [06-02|03:00:18.093] [5/15 Bodies] Processing bodies...       from=28736695 to=28738000
[INFO] [06-02|03:00:38.094] [5/15 Bodies] Downloading block bodies   block_num=28736695 delivery/sec=210.1KB wasted/sec=0B remaining=1304 delivered=97 cache=221.6MB alloc=4.7GB sys=10.3GB
[INFO] [06-02|03:00:41.582] [snapshots] Blocks Stat                  blocks=28646k indices=28646k alloc=4.9GB sys=10.3GB
[INFO] [06-02|03:00:58.094] [5/15 Bodies] Downloading block bodies   block_num=28736747 delivery/sec=260.6KB wasted/sec=0B remaining=1252 delivered=227 cache=224.7MB alloc=5.3GB sys=10.3GB
[INFO] [06-02|03:01:09.332] [p2p] GoodPeers                          eth66=936
[INFO] [06-02|03:01:10.689] [txpool] stat                            pending=10000 baseFee=1 queued=30000 alloc=5.6GB sys=10.3GB
[INFO] [06-02|03:01:18.093] [5/15 Bodies] No block bodies to write in this log period block number=28736747
[INFO] [06-02|03:01:38.093] [5/15 Bodies] No block bodies to write in this log period block number=28736747
[INFO] [06-02|03:01:58.093] [5/15 Bodies] No block bodies to write in this log period block number=28736747
[INFO] [06-02|03:02:10.669] [txpool] stat                            pending=10000 baseFee=1 queued=30000 alloc=4.5GB sys=10.3GB
[INFO] [06-02|03:02:18.093] [5/15 Bodies] No block bodies to write in this log period block number=28736747
[INFO] [06-02|03:02:38.094] [5/15 Bodies] Downloading block bodies   block_num=28736747 delivery/sec=102.6KB wasted/sec=0B remaining=1252 delivered=272 cache=226.7MB alloc=5.2GB sys=10.3GB```

**Comment by fylsan3** [comment]
删除 --staticpeers 和 --p2p.protocol=66 试下 我遇到过，删掉这两个就好了

**Comment by icculp** [comment]
Has been stable for a few days, will reopen if I encounter any more issues
