### ISSUE TITLE
On sync error erigon jumps back to previous unwind block

### ISSUE THREAD

**Issue by Doc-Pixel** [node-real/bsc-erigon#120]
#### System information

Erigon version: `./erigon --version`
1.07 (started out with 1.04 weeks ago)

OS & Version: Windows/Linux/OSX
Linux ubuntu 22.04

Commit hash: 

Erigon Command (with flags/config):
ExecStart=/opt/erigon/erigon --chain bsc --torrent.download.rate 250mb --torrent.upload.rate 50mb --datadir /data/erigon  --maxpeers 30 --log.dir.path /data/erigon --sentry.drop-useless-peers --batchSize 2048M --db.pagesize 16k

Concensus Layer:
N/A

Concensus Layer Command (with flags/config):
N/A

Chain/Network: 
BSC mainnet

#### Expected behaviour
erigon syncs to the tip of the chain after unwind. bodies written in step 5/15 are preserved on a restart.

#### Actual behaviour
Erigon writes block bodies for days in step 5/15, proceeds to fail on 7/15 and unwinds to the block I specified earlier to fix a stuck block.
```
[INFO] [06-04|08:01:53.657] [7/15 Execution] Blocks execution        from=22994999 to=28608503
[WARN] [06-04|08:01:58.003] [7/15 Execution] Execution failed        block=22995000 hash=0x6935da1ca4365dd69f554df161b5573ca36abad7d413772cdbf4672153e08d37 err="mismatching validator list on epoch block"
[INFO] [06-04|08:01:58.003] UnwindTo                                 block=22994999 bad_block_hash=0x6935da1ca4365dd69f554df161b5573ca36abad7d413772cdbf4672153e08d37
[INFO] [06-04|08:01:58.003] [7/15 Execution] Completed on            block=22994999
```

#### Steps to reproduce the behaviour
Sync erigon, unwind on a block error, restart sync, wait until failure in step 7/15, observe the rollback to the previous unwind

**Comment by calmbeing** [comment]
same issue with https://github.com/node-real/bsc-erigon/issues/119, should be resolved, close here. Please reopen if still problem
