### ISSUE TITLE
please upgrade migrator.VerifyVersion

### ISSUE THREAD

**Issue by SuperEdison** [node-real/bsc-erigon#141]
#### System information

Erigon version: `./erigon --version`
v1.1.1

OS & Version: Windows/Linux/OSX
linux
Commit hash: 

Erigon Command (with flags/config):

Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network: 
bsc
#### Actual behaviour
EROR[06-23|10:58:16.686] Erigon startup                           err="migrator.VerifyVersion: cannot downgrade minor DB version from 6.1 to 6.6"

#### Backtrace

````
[backtrace]
````

**Comment by blxdyx** [comment]
Please show your start command and more logs
