### ISSUE TITLE
Node is lagging to sync

### ISSUE THREAD

**Issue by simpsoncarlos3** [node-real/bsc-erigon#15]
#### System information

Erigon version: `./erigon --version`
erigon version 2.40.0-dev

OS & Version: Windows/Linux/OSX
Linux

Commit hash: 

Erigon Command (with flags/config):
erigon --chain=bsc --datadir=/srv/svc --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --private.api.addr=0.0.0.0:9090 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061 --http.api=eth,erigon,web3,net,debug,trace,txpool,parity,bor --prune htrc --ws

Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network: 56 Mainnet

#### Expected behaviour
it should sync to the currentblock

#### Actual behaviour
it is lagging a few blocks to sync

#### Steps to reproduce the behaviour
just download and sync

#### Backtrace

````
[backtrace]
````

Hello there,
My nodereal erigon build is lagging to sync for about 2 weeks now.
once in every few blocks sync it displays like this

[INFO] [04-11|03:35:14.497] [5/15 Bodies] No block bodies to write in this log period block number=27241889
[INFO] [04-11|03:35:34.498] [5/15 Bodies] No block bodies to write in this log period block number=27241889

and waits  for a few seconds and catchup to the current block

and then it occurs again.

it is delaying

**Comment by blxdyx** [comment]
You can try add this command:
`--bodies.cache=214748364800 --batchSize=4096M --db.pagesize=16k `
This will speed up the download and execute stage.

**Comment by blxdyx** [comment]
Try unwind some blocks and reboot again.

**Comment by calmbeing** [comment]
Suggest to use the latest mdbx snapshot for archive node: https://github.com/bnb-chain/bsc-snapshots
