### ISSUE TITLE
Erigon-lib dependency in go.mod

### ISSUE THREAD

**Issue by IvanLazarevsky** [node-real/bsc-erigon#164]
Current erigon-lib dependency is **github.com/calmbeing/bsc-erigon-lib** instead of expected **github.com/node-real/bsc-erigon-lib**. Not a major problem, but as we maintain yet another fork, this change required us to track another upstream. Are there plans to merge the former into the latter?

**Comment by calmbeing** [comment]
Solved https://github.com/node-real/bsc-erigon/commit/e74c0014a2de3a5b3ad6a5dd9b1234cf27c452c5
