### ISSUE TITLE
the log show error message，I don't know how to fix it

### ISSUE THREAD

**Issue by kindesa** [node-real/bsc-erigon#184]
#### System information

Erigon version: `v1.1.7`

OS & Version: Ubuntu Server 22.04 LTS 64

Erigon Command (with flags/config):
/data/erigon/build/bin/erigon --datadir=/mnt/data/bscchaindata --chain=bsc --http.addr=0.0.0.0 --http.port=80 --http.api=eth,erigon,engine,web3,trace --bodies.cache=2g --batchSize=1g --etl.bufferSize=1g --http.vhosts=* --rpc.batch.concurrency=32 --db.read.concurrency=64 --http=true --prune=hrtc --db.pagesize=16k

Chain/Network: mainnet

I found the log show "
[downloader] Rejected header marked as bad hash=0x5d38b4736b4b96a2506778f5bd722e13923aa98ecf77e09b8fe889dfeeb030db" yestoday,
so I upgrade the erigon version v1.1.5 -> v.1.17,
when I restart it, the log show:
'''
[EROR] [08-11|12:42:09.524] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750143
[EROR] [08-11|12:42:09.527] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750144
[EROR] [08-11|12:42:09.530] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750145
[EROR] [08-11|12:42:09.532] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750146
[EROR] [08-11|12:42:09.533] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750147
[EROR] [08-11|12:42:09.534] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750148
[EROR] [08-11|12:42:09.536] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750149
[EROR] [08-11|12:42:09.538] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750150
[EROR] [08-11|12:42:09.540] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750151
[EROR] [08-11|12:42:09.542] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750152
[EROR] [08-11|12:42:09.544] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750153
[EROR] [08-11|12:42:09.547] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750154
[EROR] [08-11|12:42:09.549] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750155
[EROR] [08-11|12:42:09.551] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750156
[EROR] [08-11|12:42:09.553] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750157
[EROR] [08-11|12:42:09.555] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750158
[EROR] [08-11|12:42:09.557] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750159
[EROR] [08-11|12:42:09.560] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750160
[EROR] [08-11|12:42:09.562] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750161
[EROR] [08-11|12:42:09.563] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750162
[EROR] [08-11|12:42:09.564] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750163
[EROR] [08-11|12:42:09.566] FeedHeaderPoW Get highestHeader fail     err=nil hd.highestInDb=30750164
[INFO] [08-11|12:42:09.568] [2/15 Headers] Processed                 highest inserted=30750164 age=3s
[INFO] [08-11|12:42:11.062] [5/15 Bodies] Processing bodies...       from=30749535 to=30750164
[INFO] [08-11|12:42:31.064] [5/15 Bodies] Downloading block bodies   block_num=30749658 delivery/sec=670.0KB wasted/sec=0B remaining=505 delivered=330 cache=13.3MB alloc=3.4GB sys=6.2GB
[INFO] [08-11|12:42:47.298] [5/15 Bodies] Processed                  highest=30750164
[INFO] [08-11|12:42:47.299] [6/15 Senders] Started                   from=30749535 to=30750164
[INFO] [08-11|12:42:50.590] [7/15 Execution] Blocks execution        from=30749535 to=30750164
[INFO] [08-11|12:43:10.725] [7/15 Execution] Executed blocks         number=30749555 blk/s=1.0 tx/s=118.7 Mgas/s=11.6 gasState=0.00 batch=328.3KB alloc=3.8GB sys=6.2GB
[INFO] [08-11|12:43:25.281] [p2p] GoodPeers                          eth67=12 eth66=19 eth68=13
[INFO] [08-11|12:43:31.232] [7/15 Execution] Executed blocks         number=30749586 blk/s=1.5 tx/s=185.7 Mgas/s=18.9 gasState=0.00 batch=1.0MB alloc=4.0GB sys=6.2GB
[INFO] [08-11|12:43:50.783] [7/15 Execution] Executed blocks         number=30749610 blk/s=1.2 tx/s=150.8 Mgas/s=17.1 gasState=0.00 batch=1.6MB alloc=3.4GB sys=6.2GB
[INFO] [08-11|12:44:10.814] [7/15 Execution] Executed blocks         number=30749648 blk/s=1.9 tx/s=234.0 Mgas/s=24.4 gasState=0.00 batch=2.5MB alloc=3.6GB sys=6.2GB
[INFO] [08-11|12:44:31.522] [7/15 Execution] Executed blocks         number=30749680 blk/s=1.5 tx/s=191.3 Mgas/s=25.3 gasState=0.00 batch=3.4MB alloc=3.9GB sys=6.2GB
[INFO] [08-11|12:44:50.907] [7/15 Execution] Executed blocks         number=30749715 blk/s=1.8 tx/s=216.0 Mgas/s=27.2 gasState=0.00 batch=4.3MB alloc=4.1GB sys=6.2GB
[INFO] [08-11|12:45:11.171] [7/15 Execution] Executed blocks         number=30749754 blk/s=1.9 tx/s=237.1 Mgas/s=27.7 gasState=0.00 batch=5.3MB alloc=4.4GB sys=6.2GB
[INFO] [08-11|12:45:25.281] [p2p] GoodPeers                          eth66=20 eth67=12 eth68=13
[INFO] [08-11|12:45:30.627] [7/15 Execution] Executed blocks         number=30749790 blk/s=1.9 tx/s=227.5 Mgas/s=28.8 gasState=0.00 batch=6.3MB alloc=4.7GB sys=6.2GB
[INFO] [08-11|12:45:50.949] [7/15 Execution] Executed blocks         number=30749823 blk/s=1.6 tx/s=199.1 Mgas/s=24.9 gasState=0.00 batch=7.2MB alloc=3.3GB sys=6.2GB
[INFO] [08-11|12:46:12.579] [7/15 Execution] Executed blocks         number=30749856 blk/s=1.5 tx/s=181.0 Mgas/s=28.9 gasState=0.00 batch=8.2MB alloc=3.6GB sys=6.2GB
[INFO] [08-11|12:46:30.885] [7/15 Execution] Executed blocks         number=30749899 blk/s=2.3 tx/s=288.0 Mgas/s=32.5 gasState=0.00 batch=9.4MB alloc=3.9GB sys=6.2GB
[INFO] [08-11|12:46:50.703] [7/15 Execution] Executed blocks         number=30749948 blk/s=2.5 tx/s=326.4 Mgas/s=32.7 gasState=0.00 batch=10.7MB alloc=4.2GB sys=6.2GB
[INFO] [08-11|12:47:10.875] [7/15 Execution] Executed blocks         number=30749994 blk/s=2.3 tx/s=286.8 Mgas/s=35.7 gasState=0.00 batch=12.1MB alloc=4.5GB sys=6.2GB
'''
it looks like still working, but I don't know how to fix the error "FeedHeaderPoW Get highestHeader fail"

**Comment by pilab-gwon** [comment]
devel branch is normal now

**Comment by kindesa** [comment]
it works,thanks
