### ISSUE TITLE
[2/15 Headers] No block headers to write in this log period block number=27281023

### ISSUE THREAD

**Issue by harveyff** [node-real/bsc-erigon#20]
hi

Thanks for your great work, I switched bsc to this branch, but still can't sync blocks normally, stuck at a block before the hard fork. please help me.

```
[INFO] [04-12|11:27:45.847] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=17 skelMin=27281022 skelMax=27318078 resp=103 respMin=27280978 respMax=27281022 dups=90
[INFO] [04-12|11:28:05.294] [p2p] GoodPeers                          eth67=1 eth66=25
[INFO] [04-12|11:28:05.811] [txpool] stat                            pending=11 baseFee=0 queued=22 alloc=2.7GB sys=4.0GB
[INFO] [04-12|11:28:05.848] [2/15 Headers] No block headers to write in this log period block number=27281023
[INFO] [04-12|11:28:05.848] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=17 skelMin=27281022 skelMax=27318078 resp=102 respMin=27281022 respMax=27281022 dups=99
[INFO] [04-12|11:28:25.848] [2/15 Headers] No block headers to write in this log period block number=27281023
[INFO] [04-12|11:28:25.848] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=17 skelMin=27281022 skelMax=27318078 resp=102 respMin=27281022 respMax=27281022 dups=88
[INFO] [04-12|11:28:45.848] [2/15 Headers] No block headers to write in this log period block number=27281023
[INFO] [04-12|11:28:45.848] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=17 skelMin=27281022 skelMax=27318078 resp=102 respMin=27281022 respMax=27281022 dups=95
[INFO] [04-12|11:29:05.812] [txpool] stat                            pending=11 baseFee=0 queued=24 alloc=3.0GB sys=4.0GB
[INFO] [04-12|11:29:05.847] [2/15 Headers] No block headers to write in this log period block number=27281023
[INFO] [04-12|11:29:05.847] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=17 skelMin=27281022 skelMax=27318078 resp=102 respMin=27281022 respMax=27281022 dups=90
[INFO] [04-12|11:29:25.848] [2/15 Headers] No block headers to write in this log period block number=27281023
[INFO] [04-12|11:29:25.848] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=17 skelMin=27281022 skelMax=27318078 resp=102 respMin=27281022 respMax=27281022 dups=92
[INFO] [04-12|11:29:45.848] [2/15 Headers] No block headers to write in this log period block number=27281023
[INFO] [04-12|11:29:45.848] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=17 skelMin=27281022 skelMax=27318078 resp=102 respMin=27281022 respMax=27281022 dups=88
[INFO] [04-12|11:30:05.294] [p2p] GoodPeers                          eth66=29 eth67=1
[INFO] [04-12|11:30:05.811] [txpool] stat                            pending=12 baseFee=0 queued=25 alloc=2.5GB sys=4.0GB
[INFO] [04-12|11:30:05.848] [2/15 Headers] No block headers to write in this log period block number=27281023
[INFO] [04-12|11:30:05.848] Req/resp stats                           req=0 reqMin=0 reqMax=0 skel=17 skelMin=27281022 skelMax=27318078 resp=106 respMin=27280978 respMax=27281022 dups=94

```

**Comment by calmbeing** [comment]
Please restart, there's p2p problem at that time

**Comment by barryz** [comment]
Same problem we've encountered.


```
[04-12|14:44:00.612] [snapshots] Blocks Stat                  blocks=27191k indices=27191k alloc=2.5GB sys=3.2GB
[INFO] [04-12|14:44:00.614] [2/15 Headers] Waiting for headers...    from=27281022
[INFO] [04-12|14:44:20.614] [2/15 Headers] Wrote block headers       number=27285267 blk/second=212.250 alloc=2.9GB sys=3.2GB
[INFO] [04-12|14:44:40.614] [2/15 Headers] No block headers to write in this log period block number=27285267
[INFO] [04-12|14:45:00.614] [2/15 Headers] No block headers to write in this log period block number=27285267
[INFO] [04-12|14:45:20.614] [2/15 Headers] No block headers to write in this log period block number=27285267

```

Restarting the node does not help.

**Comment by AdminAnticaptcha** [comment]
Try to unwind a few blocks back.

make integration

```
integration state_stages --unwind=20 --chain=bsc --datadir=/path
integration stage_headers --unwind=20 --chain=bsc --datadir=/path
```

Had to interrupt first command manually first command after 20 loops.

Node works normally for me at the moment.

**Comment by barryz** [comment]
> Try to unwind a few blocks back.
> 
> make integration
> 
> ```
> integration state_stages --unwind=20 --chain=bsc --datadir=/path
> integration stage_headers --unwind=20 --chain=bsc --datadir=/path
> ```
> 
> Had to interrupt first command manually first command after 20 loops.
> 
> Node works normally for me at the moment.

Thanks. Node works normally for me now.

**Comment by harveyff** [comment]
Hi, thanks, it's working now, but from the logs it looks like there is a problem with the block rate, it's not consistent, it often falls behind some blocks. Is there something wrong with my start command?

My machine has enough performance, 16-core 64G, 7T nvme.

```
./build/bin/erigon --datadir=/data/bsc --chain=bsc --port=30303 --http.port=8545 --authrpc.port=8551 --torrent.port=42069 --private.api.addr=127.0.0.1:9090 --http --ws --http.api=web3,net,eth,debug,trace,txpool --http.corsdomain=* --http.addr=0.0.0.0 --http.vhosts=* --snapshots=false bootnodes=enode://1cc4534b14cfe351ab740a1418ab944a234ca2f702915eadb7e558a02010cb7c5a8c295a3b56bcefa7701c07752acd5539cb13df2aab8ae2d98934d712611443@52.71.43.172:30311,enode://28b1d16562dac280dacaaf45d54516b85bc6c994252a9825c5cc4e080d3e53446d05f63ba495ea7d44d6c316b54cd92b245c5c328c37da24605c4a93a0d099c4@34.246.65.14:30311,enode://5a7b996048d1b0a07683a949662c87c09b55247ce774aeee10bb886892e586e3c604564393292e38ef43c023ee9981e1f8b335766ec4f0f256e57f8640b079d5@35.73.137.11:30311
```

```
[INFO] [04-13|03:38:23.364] [2/15 Headers] Waiting for headers...    from=27301453
[INFO] [04-13|03:38:31.507] [2/15 Headers] Processed                 highest inserted=27301460 age=8s
[INFO] [04-13|03:38:33.484] [7/15 Execution] Completed on            block=27301460
[INFO] [04-13|03:38:40.259] Commit cycle                             in=942.937946ms
[INFO] [04-13|03:38:40.259] Timings (slower than 50ms)               Headers=8.142s Bodies=451ms Senders=63ms Execution=1.457s HashState=1.253s IntermediateHashes=1.931s CallTraces=478ms AccountHistoryIndex=341ms StorageHistoryIndex=851ms LogIndex=600ms TxLookup=374ms
[INFO] [04-13|03:38:40.259] Tables                                   PlainState=217.0GB AccountChangeSet=529.0GB StorageChangeSet=1.2TB BlockTransaction=3.8GB TransactionLog=2.2TB FreeList=8.0MB ReclaimableSpace=31.8GB
[INFO] [04-13|03:38:40.259] RPC Daemon notified of new headers       from=27301453 to=27301460 hash=0x6f4f691c36253410e2bf10b92382ee6930c3844c50d3bb06e8832409596f19a7 header sending=29.924µs log sending=345ns
[INFO] [04-13|03:38:40.468] [2/15 Headers] Waiting for headers...    from=27301460
[INFO] [04-13|03:38:46.691] [2/15 Headers] Processed                 highest inserted=27301466 age=5s
[INFO] [04-13|03:38:48.903] [7/15 Execution] Completed on            block=27301466
[INFO] [04-13|03:38:54.911] Commit cycle                             in=836.748435ms
[INFO] [04-13|03:38:54.911] Timings (slower than 50ms)               Headers=6.222s Bodies=808ms Execution=1.356s HashState=1.201s IntermediateHashes=1.863s CallTraces=502ms AccountHistoryIndex=347ms StorageHistoryIndex=602ms LogIndex=373ms TxLookup=279ms
[INFO] [04-13|03:38:54.911] Tables                                   PlainState=217.0GB AccountChangeSet=529.0GB StorageChangeSet=1.2TB BlockTransaction=3.8GB TransactionLog=2.2TB FreeList=8.0MB ReclaimableSpace=31.8GB
[INFO] [04-13|03:38:54.911] RPC Daemon notified of new headers       from=27301460 to=27301466 hash=0xfb17e42f7cdc80bf3ae7f8ab73e4efb8f15402f5f512213f683d76cb2e6d006d header sending=25.674µs log sending=255ns
[INFO] [04-13|03:38:55.485] [2/15 Headers] Waiting for headers...    from=27301466
[INFO] [04-13|03:39:05.125] [2/15 Headers] Processed                 highest inserted=27301471 age=9s
[INFO] [04-13|03:39:06.895] [7/15 Execution] Completed on            block=27301471
[INFO] [04-13|03:39:11.078] Commit cycle                             in=655.840563ms
[INFO] [04-13|03:39:11.078] Timings (slower than 50ms)               Headers=9.64s Bodies=880ms Execution=853ms HashState=793ms IntermediateHashes=1.251s CallTraces=311ms AccountHistoryIndex=205ms StorageHistoryIndex=452ms LogIndex=308ms TxLookup=204ms
[INFO] [04-13|03:39:11.078] Tables                                   PlainState=217.0GB AccountChangeSet=529.0GB StorageChangeSet=1.2TB BlockTransaction=3.8GB TransactionLog=2.2TB FreeList=8.0MB ReclaimableSpace=31.8GB
[INFO] [04-13|03:39:11.078] RPC Daemon notified of new headers       from=27301466 to=27301471 hash=0x224ab1c3f6bf7055f4deedee890e9ccbfcbac967fba5f922ed0c280ca3d66733 header sending=46.317µs log sending=238ns
[INFO] [04-13|03:39:11.513] [2/15 Headers] Waiting for headers...    from=27301471
[INFO] [04-13|03:39:14.364] [txpool] stat                            pending=5856 baseFee=117 queued=4579 alloc=5.2GB sys=9.1GB
[INFO] [04-13|03:39:23.326] [2/15 Headers] Processed                 highest inserted=27301478 age=6s
[INFO] [04-13|03:39:25.179] [7/15 Execution] Completed on            block=27301478
[INFO] [04-13|03:39:31.468] Commit cycle                             in=824.15405ms
[INFO] [04-13|03:39:31.468] Timings (slower than 50ms)               Headers=11.813s Bodies=479ms Senders=119ms Execution=1.247s HashState=1.007s IntermediateHashes=1.918s CallTraces=625ms AccountHistoryIndex=497ms StorageHistoryIndex=614ms LogIndex=289ms TxLookup=511ms
[INFO] [04-13|03:39:31.468] Tables                                   PlainState=217.0GB AccountChangeSet=529.0GB StorageChangeSet=1.2TB BlockTransaction=3.8GB TransactionLog=2.2TB FreeList=8.0MB ReclaimableSpace=31.8GB
[INFO] [04-13|03:39:31.468] RPC Daemon notified of new headers       from=27301471 to=27301478 hash=0x614dc8ec29322acdfe966de474caaf2e5461999965e1ddc9a388286a9eb2d6ce header sending=31.22µs log sending=254ns
[INFO] [04-13|03:39:32.053] [2/15 Headers] Waiting for headers...    from=27301478
[INFO] [04-13|03:39:52.054] [2/15 Headers] Wrote block headers       number=27301484 blk/second=0.300 alloc=4.4GB sys=9.1GB
[INFO] [04-13|03:39:59.223] [2/15 Headers] Processed                 highest inserted=27301490 age=6s
[INFO] [04-13|03:40:03.476] [7/15 Execution] Completed on            block=27301490
[INFO] [04-13|03:40:12.340] [p2p] GoodPeers                          eth68=11 eth66=29
[INFO] [04-13|03:40:14.368] [txpool] stat                            pending=6840 baseFee=117 queued=4593 alloc=4.9GB sys=9.1GB
[INFO] [04-13|03:40:15.713] Commit cycle                             in=1.473092024s
[INFO] [04-13|03:40:15.713] Timings (slower than 50ms)               Headers=27.17s Bodies=1.092s Senders=80ms Execution=3.067s HashState=2.412s IntermediateHashes=3.822s CallTraces=1.047s AccountHistoryIndex=748ms StorageHistoryIndex=1.297s LogIndex=773ms TxLookup=663ms
[INFO] [04-13|03:40:15.713] Tables                                   PlainState=217.0GB AccountChangeSet=529.0GB StorageChangeSet=1.2TB BlockTransaction=3.8GB TransactionLog=2.2TB FreeList=8.0MB ReclaimableSpace=31.9GB
[INFO] [04-13|03:40:15.713] RPC Daemon notified of new headers       from=27301478 to=27301490 hash=0xad1353592cf4b1102dbb2fe353352abf42734ac3761cca47c01a874541140466 header sending=34.715µs log sending=246ns

```

**Comment by simpsoncarlos3** [comment]
> Hi, thanks, it's working now, but from the logs it looks like there is a problem with the block rate, it's not consistent, it often falls behind some blocks. Is there something wrong with my start command?
> 
> My machine has enough performance, 16-core 64G, 7T nvme.
> 
> ```
> ./build/bin/erigon --datadir=/data/bsc --chain=bsc --port=30303 --http.port=8545 --authrpc.port=8551 --torrent.port=42069 --private.api.addr=127.0.0.1:9090 --http --ws --http.api=web3,net,eth,debug,trace,txpool --http.corsdomain=* --http.addr=0.0.0.0 --http.vhosts=* --snapshots=false bootnodes=enode://1cc4534b14cfe351ab740a1418ab944a234ca2f702915eadb7e558a02010cb7c5a8c295a3b56bcefa7701c07752acd5539cb13df2aab8ae2d98934d712611443@52.71.43.172:30311,enode://28b1d16562dac280dacaaf45d54516b85bc6c994252a9825c5cc4e080d3e53446d05f63ba495ea7d44d6c316b54cd92b245c5c328c37da24605c4a93a0d099c4@34.246.65.14:30311,enode://5a7b996048d1b0a07683a949662c87c09b55247ce774aeee10bb886892e586e3c604564393292e38ef43c023ee9981e1f8b335766ec4f0f256e57f8640b079d5@35.73.137.11:30311
> ```
> 
> ```
> [INFO] [04-13|03:38:23.364] [2/15 Headers] Waiting for headers...    from=27301453
> [INFO] [04-13|03:38:31.507] [2/15 Headers] Processed                 highest inserted=27301460 age=8s
> [INFO] [04-13|03:38:33.484] [7/15 Execution] Completed on            block=27301460
> [INFO] [04-13|03:38:40.259] Commit cycle                             in=942.937946ms
> [INFO] [04-13|03:38:40.259] Timings (slower than 50ms)               Headers=8.142s Bodies=451ms Senders=63ms Execution=1.457s HashState=1.253s IntermediateHashes=1.931s CallTraces=478ms AccountHistoryIndex=341ms StorageHistoryIndex=851ms LogIndex=600ms TxLookup=374ms
> [INFO] [04-13|03:38:40.259] Tables                                   PlainState=217.0GB AccountChangeSet=529.0GB StorageChangeSet=1.2TB BlockTransaction=3.8GB TransactionLog=2.2TB FreeList=8.0MB ReclaimableSpace=31.8GB
> [INFO] [04-13|03:38:40.259] RPC Daemon notified of new headers       from=27301453 to=27301460 hash=0x6f4f691c36253410e2bf10b92382ee6930c3844c50d3bb06e8832409596f19a7 header sending=29.924µs log sending=345ns
> [INFO] [04-13|03:38:40.468] [2/15 Headers] Waiting for headers...    from=27301460
> [INFO] [04-13|03:38:46.691] [2/15 Headers] Processed                 highest inserted=27301466 age=5s
> [INFO] [04-13|03:38:48.903] [7/15 Execution] Completed on            block=27301466
> [INFO] [04-13|03:38:54.911] Commit cycle                             in=836.748435ms
> [INFO] [04-13|03:38:54.911] Timings (slower than 50ms)               Headers=6.222s Bodies=808ms Execution=1.356s HashState=1.201s IntermediateHashes=1.863s CallTraces=502ms AccountHistoryIndex=347ms StorageHistoryIndex=602ms LogIndex=373ms TxLookup=279ms
> [INFO] [04-13|03:38:54.911] Tables                                   PlainState=217.0GB AccountChangeSet=529.0GB StorageChangeSet=1.2TB BlockTransaction=3.8GB TransactionLog=2.2TB FreeList=8.0MB ReclaimableSpace=31.8GB
> [INFO] [04-13|03:38:54.911] RPC Daemon notified of new headers       from=27301460 to=27301466 hash=0xfb17e42f7cdc80bf3ae7f8ab73e4efb8f15402f5f512213f683d76cb2e6d006d header sending=25.674µs log sending=255ns
> [INFO] [04-13|03:38:55.485] [2/15 Headers] Waiting for headers...    from=27301466
> [INFO] [04-13|03:39:05.125] [2/15 Headers] Processed                 highest inserted=27301471 age=9s
> [INFO] [04-13|03:39:06.895] [7/15 Execution] Completed on            block=27301471
> [INFO] [04-13|03:39:11.078] Commit cycle                             in=655.840563ms
> [INFO] [04-13|03:39:11.078] Timings (slower than 50ms)               Headers=9.64s Bodies=880ms Execution=853ms HashState=793ms IntermediateHashes=1.251s CallTraces=311ms AccountHistoryIndex=205ms StorageHistoryIndex=452ms LogIndex=308ms TxLookup=204ms
> [INFO] [04-13|03:39:11.078] Tables                                   PlainState=217.0GB AccountChangeSet=529.0GB StorageChangeSet=1.2TB BlockTransaction=3.8GB TransactionLog=2.2TB FreeList=8.0MB ReclaimableSpace=31.8GB
> [INFO] [04-13|03:39:11.078] RPC Daemon notified of new headers       from=27301466 to=27301471 hash=0x224ab1c3f6bf7055f4deedee890e9ccbfcbac967fba5f922ed0c280ca3d66733 header sending=46.317µs log sending=238ns
> [INFO] [04-13|03:39:11.513] [2/15 Headers] Waiting for headers...    from=27301471
> [INFO] [04-13|03:39:14.364] [txpool] stat                            pending=5856 baseFee=117 queued=4579 alloc=5.2GB sys=9.1GB
> [INFO] [04-13|03:39:23.326] [2/15 Headers] Processed                 highest inserted=27301478 age=6s
> [INFO] [04-13|03:39:25.179] [7/15 Execution] Completed on            block=27301478
> [INFO] [04-13|03:39:31.468] Commit cycle                             in=824.15405ms
> [INFO] [04-13|03:39:31.468] Timings (slower than 50ms)               Headers=11.813s Bodies=479ms Senders=119ms Execution=1.247s HashState=1.007s IntermediateHashes=1.918s CallTraces=625ms AccountHistoryIndex=497ms StorageHistoryIndex=614ms LogIndex=289ms TxLookup=511ms
> [INFO] [04-13|03:39:31.468] Tables                                   PlainState=217.0GB AccountChangeSet=529.0GB StorageChangeSet=1.2TB BlockTransaction=3.8GB TransactionLog=2.2TB FreeList=8.0MB ReclaimableSpace=31.8GB
> [INFO] [04-13|03:39:31.468] RPC Daemon notified of new headers       from=27301471 to=27301478 hash=0x614dc8ec29322acdfe966de474caaf2e5461999965e1ddc9a388286a9eb2d6ce header sending=31.22µs log sending=254ns
> [INFO] [04-13|03:39:32.053] [2/15 Headers] Waiting for headers...    from=27301478
> [INFO] [04-13|03:39:52.054] [2/15 Headers] Wrote block headers       number=27301484 blk/second=0.300 alloc=4.4GB sys=9.1GB
> [INFO] [04-13|03:39:59.223] [2/15 Headers] Processed                 highest inserted=27301490 age=6s
> [INFO] [04-13|03:40:03.476] [7/15 Execution] Completed on            block=27301490
> [INFO] [04-13|03:40:12.340] [p2p] GoodPeers                          eth68=11 eth66=29
> [INFO] [04-13|03:40:14.368] [txpool] stat                            pending=6840 baseFee=117 queued=4593 alloc=4.9GB sys=9.1GB
> [INFO] [04-13|03:40:15.713] Commit cycle                             in=1.473092024s
> [INFO] [04-13|03:40:15.713] Timings (slower than 50ms)               Headers=27.17s Bodies=1.092s Senders=80ms Execution=3.067s HashState=2.412s IntermediateHashes=3.822s CallTraces=1.047s AccountHistoryIndex=748ms StorageHistoryIndex=1.297s LogIndex=773ms TxLookup=663ms
> [INFO] [04-13|03:40:15.713] Tables                                   PlainState=217.0GB AccountChangeSet=529.0GB StorageChangeSet=1.2TB BlockTransaction=3.8GB TransactionLog=2.2TB FreeList=8.0MB ReclaimableSpace=31.9GB
> [INFO] [04-13|03:40:15.713] RPC Daemon notified of new headers       from=27301478 to=27301490 hash=0xad1353592cf4b1102dbb2fe353352abf42734ac3761cca47c01a874541140466 header sending=34.715µs log sending=246ns
> ```

yes it is falling behind for me too. sometimes even 20 blocks behind

**Comment by calmbeing** [comment]
Suggest to use the latest mdbx snapshot for archive node: https://github.com/bnb-chain/bsc-snapshots
