### ISSUE TITLE
`trace_block` no longer works after Hertz upgrade

### ISSUE THREAD

**Issue by 0xStrobe** [node-real/bsc-erigon#211]
#### System information

Erigon version: `1.1.9-dev-4b352f69`

OS & Version: Linux

Commit hash: `4b352f69`

Erigon Command (with flags/config):

```
./erigon --chain=bsc --port=xxx --sentry.drop-useless-peers --torrent.port=xxx --torrent.upload.rate=15mb --torrent.download.rate=1024mb --txpool.disable --metrics.addr=0.0.0.0 --metrics.port=xxx --db.pagesize=16k --db.read.concurrency 192 --datadir=/xxx/bsc-erigon/data --private.api.addr=localhost:xxx
```

Chain/Network: BSC

#### Expected behaviour

When sending an RPC request with method call `trace_block`, the erigon node should return trace entries of the block.

Example request:

```jsonc
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "trace_block",
  "params": [
    "0x1dda1a0" // this is block 31302048
  ]
}
```

#### Actual behaviour

Erigon responds with an error. It seems that the Hertz upgrade has not been correctly implemented.

```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "convert tx into msg: eip-1559 transactions require London"
    }
}
```

**Comment by Mister-EA** [comment]
@0xStrobe Did you make sure Berlin, London and Hertz blocks are set at the same height?

**Comment by 0xStrobe** [comment]
> @0xStrobe Did you make sure Berlin, London and Hertz blocks are set at the same height?

what do you mean specifically? i didn't manually configure that

**Comment by 0xStrobe** [comment]
anything i could do from the user's side to help u debug and identify this issue? :)

**Comment by 0xStrobe** [comment]
> As a temporary fix, can use --snap.stop, It will stop move historical data from DB to new immutable snapshots.

Will this fix the past blocks or only will be fixing the new ones from now?

**Comment by 0xStrobe** [comment]
Meanwhile I have started a new node based on the [snapshots the Ankr team published](https://chainsnap.io/#get-access-now), now I'm getting a different error when requesting block `31302048` (the json req payload is same as the OP):

```json
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"first run for txIndex 0 error: nonce too high: address 0xD98eA98A4aCC0eAcF180c75600e365867D13b51c, tx: 1 state: 0"}}
```

This is also true for the official Ankr RPC, if you send this request:

```bash
curl --request POST \
  --url https://rpc.ankr.com/bsc \
  --header 'Content-Type: application/json' \
  --data '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "trace_block",
    "params": [
      "0x1dda1a0"
    ]
}'
```

So in summary to make clear of the context, since this issue has been open for a while -

1. I started a node using the MDBX snapshot published here - https://github.com/bnb-chain/bsc-snapshots. I documented the workflow of exactly the steps I took here - https://github.com/bnb-chain/bsc-snapshots/issues/253#issuecomment-1581423408
1. The node was running for a few months, erigon updates were always successfully applied during this time
1. Node was upgraded to [v1.1.6](https://github.com/node-real/bsc-erigon/releases/tag/v1.1.6), in preparation for the Hertz upgrade
1. I observed that all trace block calls have failed after the Hertz upgrade at block `31302048`. I upgraded it to the latest `v1.1.9`, but kept receiving error as in OP: `convert tx into msg: eip-1559 transactions require London` (I don't remember what error v1.1.6 gave at that time)
1. The tx logs API etc seem to be okay, although the trace API errors out
1. After doing research, I thought there might be an issue with the way I bootstrapped my node, so I downloaded Ankr's snapshot from Chainsnap. Today I started a new server, and attempted to request the same `trace_block`, and I got the error `first run for txIndex 0 error: nonce too high: address 0xD98eA98A4aCC0eAcF180c75600e365867D13b51c, tx: 1 state: 0` instead.
1. I checked with the official Ankr RPC endpoint, they return the identical error, ruling out that I didn't bootstrap it correctly

**Comment by 0xStrobe** [comment]
> > > As a temporary fix, can use --snap.stop, It will stop move historical data from DB to new immutable snapshots.
> > 
> > 
> > Will this fix the past blocks or only will be fixing the new ones from now?
> 
> the new ones

Thank you, is there a way to fix and backfill the faulty blocks since the Hertz hard fork?

**Comment by 0xStrobe** [comment]
> > > > > As a temporary fix, can use --snap.stop, It will stop move historical data from DB to new immutable snapshots.
> > > > 
> > > > 
> > > > Will this fix the past blocks or only will be fixing the new ones from now?
> > > 
> > > 
> > > the new ones
> > 
> > 
> > Thank you, is there a way to fix and backfill the faulty blocks since the Hertz hard fork?
> 
> You can try to sync from snapshot before Hertz hard fork with this flag

Is there a way to reset an updated node to a block before Hertz then sync from there? Unfortunately I can't find a snapshot before Hertz anymore, there is this one but it's very up to date - https://github.com/bnb-chain/bsc-snapshots#endpointmainnet-update-bi-weekly

**Comment by 0xStrobe** [comment]
Syncing with the latest commit in devel, will report back

**Comment by 0xStrobe** [comment]
> ```js
> {
>   "jsonrpc": "2.0",
>   "id": 1,
>   "method": "trace_block",
>   "params": [
>     "0x1dda1a0" // this is block 31302048
>   ]
> }
> ```

Thank you! I forgot to delete /snapshots/db but ran all the other stuff and synced... The block I used in the OP is working with traces now (block 0x1dda1a0).

However to be completely sure, I will delete `/snapshots/db` now and redo the steps and report back to confirm.
