### ISSUE TITLE
node not syncing 

### ISSUE THREAD

**Issue by zakirgl** [node-real/bsc-erigon#219]
running latest bsc node from devel branch https://github.com/node-real/bsc-erigon/commit/4b352f69f9129dc648c17fc55d8c8a5bb04e9375 
and it is not syncing we get those errors in logs 
we did unwind but that did not help 

 ./integration stage_headers —unwind=1550000 
also tried that 
 ./integration stage_headers —reset 
but did not help attaching logs below anyone can help? 

[EROR] [09-08|16:12:52.973] Staged Sync                              err="[5/15 Bodies] WriteRawBodyIfNotExists: WriteRawTransactions: txId=4739956176, baseTxId=4739956176, bucket: BlockTransaction, mdbx_cursor_put: MDBX_EKEYMISMATCH: The given key value is mismatched to the current cursor position"
[INFO] [09-08|16:12:53.736] [5/15 Bodies] Processing bodies...       from=31384999 to=31562019
[WARN] [09-08|16:12:53.845] Served                                   conn=127.0.0.1:40490 method=eth_call reqid=5444934000238409 t=143.393µs err="execution reverted"
[WARN] [09-08|16:12:53.846] Served                                   conn=127.0.0.1:40518 method=eth_call reqid=5444934000238412 t=149.861µs err="execution reverted"
[WARN] [09-08|16:12:53.847] Served                                   conn=127.0.0.1:40546 method=eth_call reqid=5444934000238415 t=101.075µs err="execution reverted"
[WARN] [09-08|16:12:53.849] Served                                   conn=127.0.0.1:40558 method=eth_call reqid=5444934000238418 t=172.54µs err="execution reverted"
[EROR] [09-08|16:12:53.868] Staged Sync                              err="[5/15 Bodies] WriteRawBodyIfNotExists: WriteRawTransactions: txId=4739956176, baseTxId=4739956176, bucket: BlockTransaction, mdbx_cursor_put: MDBX_EKEYMISMATCH: The given key value is mismatched to the current cursor position"
[WARN] [09-08|16:12:53.936] Served                                   conn=127.0.0.1:41034 method=eth_call reqid=5444934000238454 t=399.104µs err="execution reverted"
[WARN] [09-08|16:12:53.939] Served                                   conn=127.0.0.1:41064 method=eth_call reqid=5444934000238455 t=371.684µs err="execution reverted: StakerProxy: NO_ACCESS" errdata=0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000165374616b657250726f78793a204e4f5f41434345535300000000000000000000
[WARN] [09-08|16:12:53.940] Served                                   conn=127.0.0.1:41098 method=eth_call reqid=5444934000238459 t=174.893µs err="execution reverted"
[WARN] [09-08|16:12:53.940] Served                                   conn=127.0.0.1:41112 method=eth_call reqid=5444934000238460 t=165.183µs err="execution reverted"
[WARN] [09-08|16:12:53.942] Served                                   conn=127.0.0.1:41114 method=eth_call reqid=5444934000238461 t=321.412µs err="execution reverted"
[WARN] [09-08|16:12:53.943] Served                                   conn=127.0.0.1:41138 method=eth_call reqid=5444934000238463 t=278.714µs err="execution reverted"
[WARN] [09-08|16:12:53.943] Served                                   conn=127.0.0.1:41152 method=eth_call reqid=5444934000238464 t=184.903µs err="execution reverted"
[WARN] [09-08|16:12:53.943] Served                                   conn=127.0.0.1:41164 method=eth_call reqid=5444934000238465 t=157.99µs err="execution reverted"
[WARN] [09-08|16:12:53.950] Served                                   conn=127.0.0.1:41278 method=eth_call reqid=5444934000238475 t=311.604µs err="execution reverted"
[WARN] [09-08|16:12:53.961] Served                                   conn=127.0.0.1:41362 method=eth_call reqid=5444934000238484 t=322.469µs err="execution reverted: StakerProxy: NO_ACCESS" errdata=0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000165374616b657250726f78793a204e4f5f41434345535300000000000000000000

**Comment by dkeysil** [comment]
@zakirgl is this mainnet or testnet?

**Comment by zakirgl** [comment]
main
this is how i start it 
erigon --chain bsc --db.pagesize=16k \
--metrics --metrics.addr=0.0.0.0 --metrics.port=6060 \
--datadir=/opt/bsc --http --ws --http.addr="127.0.0.1" --http.port="8545" \
--http.api=eth,debug,net,trace,web3,erigon,ots --sentry.drop-useless-peers true \ 
--torrent.download.rate=500mb

**Comment by zakirgl** [comment]
thats what i did @blxdyx thanks.
