### ISSUE TITLE
Please use the latest version.

### ISSUE THREAD

**Issue by blxdyx** [node-real/bsc-erigon#260]
#### Attention

Bsc mainnet will have a herztfix hardfork 34140700. 
Please use this binary for mainnet.
[erigon_x64_v1.1.9--Build20231205](https://github.com/node-real/bsc-erigon/releases/download/v1.1.9/erigon_x64_v1.1.9--Build20231205)
[erigon_arm64_v1.1.9--Build20231205](https://github.com/node-real/bsc-erigon/releases/download/v1.1.9/erigon_arm64_v1.1.9--Build20231205)

**Comment by icculp** [comment]
Can I build from devel instead?
