### ISSUE TITLE
panic: no gaps in tx ids are allowed: block 32198715 does jump from 4827425262 to 4827425719

### ISSUE THREAD

**Issue by zformular** [node-real/bsc-erigon#263]
#### System information

Erigon version: `./erigon --version`
erigon version 1.1.10-dev

OS & Version: Windows/Linux/OSX
linux

INFO[12-12|01:23:51.265] [snapshots] Verifying                    progress=97.14%
INFO[12-12|01:24:11.270] [snapshots] Verifying                    progress=99.10%
INFO[12-12|01:24:26.234] [snapshots] Blocks Stat                  blocks=32198k indices=32198k alloc=4.5GB sys=7.3GB
INFO[12-12|01:24:26.237] [1/15 Snapshots] DONE                    in=7m34.982725245s
INFO[12-12|01:24:26.238] [2/15 Headers] Waiting for headers...    from=34276047
INFO[12-12|01:24:26.850] [2/15 Headers] Processed                 highest inserted=34276314 age=1s
INFO[12-12|01:24:27.052] [5/15 Bodies] Processing bodies...       from=34276047 to=34276314
INFO[12-12|01:24:31.715] [5/15 Bodies] Processed                  highest=34276314
INFO[12-12|01:24:31.715] [6/15 Senders] Started                   from=34276047 to=34276314
INFO[12-12|01:24:32.042] [7/15 Execution] Blocks execution        from=34276047 to=34276314
INFO[12-12|01:24:49.377] [p2p] GoodPeers                          eth66=24 eth67=5
INFO[12-12|01:24:52.180] [7/15 Execution] Executed blocks         number=34276119 blk/s=3.6 tx/s=488.3 Mgas/s=49.7 gasState=0.00 batch=1.8MB alloc=2.8GB sys=7.3GB
INFO[12-12|01:25:12.168] [7/15 Execution] Executed blocks         number=34276232 blk/s=5.7 tx/s=744.6 Mgas/s=75.8 gasState=0.00 batch=5.1MB alloc=3.6GB sys=7.3GB
INFO[12-12|01:25:30.215] [7/15 Execution] Completed on            block=34276314
INFO[12-12|01:25:30.215] [8/15 HashState] Promoting plain state   from=34276047 to=34276314
INFO[12-12|01:25:30.215] [8/15 HashState] Incremental promotion   from=34276047 to=34276314 codes=true csbucket=AccountChangeSet
INFO[12-12|01:25:35.503] [8/15 HashState] Incremental promotion   from=34276047 to=34276314 codes=false csbucket=AccountChangeSet
INFO[12-12|01:25:47.976] [8/15 HashState] Incremental promotion   from=34276047 to=34276314 codes=false csbucket=StorageChangeSet
INFO[12-12|01:26:18.128] [9/15 IntermediateHashes] Generating intermediate hashes from=34276047 to=34276314
INFO[12-12|01:26:49.377] [p2p] GoodPeers                          eth66=23 eth67=4
INFO[12-12|01:26:53.022] [9/15 IntermediateHashes] Calculating Merkle root current key=6138cf28
INFO[12-12|01:27:18.802] [9/15 IntermediateHashes] Calculating Merkle root current key=bb2dceb0
INFO[12-12|01:27:48.642] [9/15 IntermediateHashes] Calculating Merkle root current key=fabbb92c
INFO[12-12|01:27:56.114] [9/15 IntermediateHashes] DONE           in=1m37.986595019s
INFO[12-12|01:27:56.311] [10/15 CallTraces] Pruned call trace intermediate table from=34186047 to=34186313
INFO[12-12|01:28:49.377] [p2p] GoodPeers                          eth67=4 eth66=23
INFO[12-12|01:29:05.429] [12/15 StorageHistoryIndex] ETL [2/2] Loading into=StorageHistory current_prefix=cbbb3e50
INFO[12-12|01:29:09.481] [13/15 LogIndex] processing              from=34276048 to=34276314
INFO[12-12|01:29:59.537] RPC Daemon notified of new headers       from=34276047 to=34276314 hash=0x6ba31076d71d4eebd00e2289932adce024681b86fc09629b6728fe4c59c9a03b header sending=204.589µs log sending=279ns
INFO[12-12|01:29:59.537] Commit cycle                             in=2.746181318s
INFO[12-12|01:29:59.537] Timings (slower than 50ms)               Snapshots=7m34.982s Headers=613ms BlockHashes=199ms Bodies=4.663s Senders=326ms Execution=58.173s HashState=47.912s IntermediateHashes=1m37.986s CallTraces=23.606s AccountHistoryIndex=15.513s StorageHistoryIndex=34.245s LogIndex=24.376s TxLookup=22.933s
INFO[12-12|01:29:59.537] Tables                                   PlainState=251.9GB AccountChangeSet=638.1GB StorageChangeSet=1.4TB BlockTransaction=95.7GB TransactionLog=2.7TB FreeList=158.2MB ReclaimableSpace=632.7GB
INFO[12-12|01:29:59.658] [2/15 Headers] Waiting for headers...    from=34276314
INFO[12-12|01:29:59.839] [2/15 Headers] Processed                 highest inserted=34276423 age=7s
INFO[12-12|01:29:59.910] [5/15 Bodies] Processing bodies...       from=34276314 to=34276423
panic: no gaps in tx ids are allowed: block 32198715 does jump from 4827425262 to 4827425719

goroutine 562222 [running]:
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs.func3.1({0x75731569309e?, 0xc0db8d4430?, 0x8?}, {0x7573156930a6?, 0x2745040?, 0x8?})
	/go/src/github.com/node-real/bsc-erigon/turbo/snapshotsync/block_snapshots.go:1428 +0x314
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxTx).ForAmount(0x351a580?, {0x28e6b4f?, 0x2c6fa5255b103a12?}, {0xc0db8d4430, 0x8, 0xa}, 0x5f, 0xc12e7378c0)
	/root/go/pkg/mod/github.com/node-real/bsc-erigon-lib@v1.0.2-0.20231205064020-5a294bf15e2d/kv/mdbx/kv_mdbx.go:1906 +0x1a8
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs.func3({0x351a580, 0xc12d3d8120}, {0x757285d30828?, 0x8?, 0xd0?}, {0x757285d30830?, 0x27b2280?, 0xc0da5fb2a8?})
	/go/src/github.com/node-real/bsc-erigon/turbo/snapshotsync/block_snapshots.go:1425 +0x8c4
github.com/ledgerwatch/erigon-lib/kv.BigChunks.func1({0x351a580, 0xc12d3d8120})
	/root/go/pkg/mod/github.com/node-real/bsc-erigon-lib@v1.0.2-0.20231205064020-5a294bf15e2d/kv/helpers.go:70 +0x1eb
github.com/ledgerwatch/erigon-lib/kv/mdbx.(*MdbxKV).View(0xdf8475800?, {0x34fad18?, 0xc0001a8020?}, 0xc0db5f3b80)
	/root/go/pkg/mod/github.com/node-real/bsc-erigon-lib@v1.0.2-0.20231205064020-5a294bf15e2d/kv/mdbx/kv_mdbx.go:647 +0xa6
github.com/ledgerwatch/erigon-lib/kv.BigChunks({0x3503900, 0xc000b2a8f0}, {0x28d5ad6, 0xf}, {0xc0db8d4448, 0x8, 0x8}, 0xc0d945b930)
	/root/go/pkg/mod/github.com/node-real/bsc-erigon-lib@v1.0.2-0.20231205064020-5a294bf15e2d/kv/helpers.go:48 +0x192
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpTxs({0x34face0?, 0xc000b38410}, {0x3503900?, 0xc000b2a8f0}, {0xc0db8996c0, 0x38}, {0xc002168138, 0x11}, 0x1eb4d70, 0x1eb5158, ...)
	/go/src/github.com/node-real/bsc-erigon/turbo/snapshotsync/block_snapshots.go:1378 +0x910
github.com/ledgerwatch/erigon/turbo/snapshotsync.dumpBlocksRange({_, _}, _, _, {_, _}, {_, _}, {0x3503900, 0xc000b2a8f0}, ...)
	/go/src/github.com/node-real/bsc-erigon/turbo/snapshotsync/block_snapshots.go:1242 +0x625
github.com/ledgerwatch/erigon/turbo/snapshotsync.DumpBlocks({0x34face0, 0xc000b38410}, 0x1eb4d70, 0x1eb5158, 0x7a120, {0xc002168138, 0x11}, {0xc002168150, 0x16}, {0x3503900, ...}, ...)
	/go/src/github.com/node-real/bsc-erigon/turbo/snapshotsync/block_snapshots.go:1210 +0x21b
github.com/ledgerwatch/erigon/turbo/snapshotsync.retireBlocks({0x34face0, 0xc000b38410}, 0x1eb4d70, 0x1eb5158, {0x38, 0x0, 0x0, 0x0}, {0xc002168138, 0x11}, ...)
	/go/src/github.com/node-real/bsc-erigon/turbo/snapshotsync/block_snapshots.go:1164 +0x205
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocks(0xc0ade560c0, {0x34face0, 0xc000b38410}, 0x0?, 0x0?, 0x48c68e?)
	/go/src/github.com/node-real/bsc-erigon/turbo/snapshotsync/block_snapshots.go:1115 +0x125
github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground.func1()
	/go/src/github.com/node-real/bsc-erigon/turbo/snapshotsync/block_snapshots.go:1150 +0xc7
created by github.com/ledgerwatch/erigon/turbo/snapshotsync.(*BlockRetire).RetireBlocksInBackground
	/go/src/github.com/node-real/bsc-erigon/turbo/snapshotsync/block_snapshots.go:1142 +0xd3

**Comment by STdevK** [comment]
Can you share your node startup command?

**Comment by zformular** [comment]
> Can you share your node startup command?

erigon --maxpeers 100 --datadir=/cloud/block --db.pagesize=16k  --db.size.limit=16T --chain=bsc --port=30303 --torrent.download.rate=20mb --http.port=8545 --http.addr=0.0.0.0 --http.vhosts=* --torrent.port=42069 --http --ws --http.api=eth,debug,net,trace,web3,erigon,parity --rpc.batch.concurrency 40 --bodies.cache 1073741824

**Comment by zformular** [comment]
> Delete all snapshots and download from here: https://github.com/bnb-chain/bsc-snapshots#erigon_snapshots_20231130tarlz4. Then reset the header.

I've tries three times, same error
INFO[12-20|02:01:55.926] TruncateBlocks                           block=32371536
INFO[12-20|02:02:15.925] TruncateBlocks                           block=32353164
INFO[12-20|02:02:35.926] TruncateBlocks                           block=32333175
INFO[12-20|02:02:55.926] TruncateBlocks                           block=32311269
INFO[12-20|02:03:15.926] TruncateBlocks                           block=32291975
INFO[12-20|02:03:35.926] TruncateBlocks                           block=32273444
INFO[12-20|02:03:55.925] TruncateBlocks                           block=32252220
INFO[12-20|02:04:15.926] TruncateBlocks                           block=32231325
INFO[12-20|02:04:35.925] TruncateBlocks                           block=32211402
INFO[12-20|02:04:46.448] TruncateBlocks done
INFO[12-20|02:07:25.176] Clear                                    table=NonCanonicalTransaction
INFO[12-20|02:07:25.229] Clear                                    table=BlockTransaction
INFO[12-20|02:07:25.229] Clear                                    table=MaxTxNum
INFO[12-20|02:07:45.230] [fillind_db_from_snapshots] Total difficulty index: 2150k/33842k
INFO[12-20|02:08:08.607] [fillind_db_from_snapshots] Total difficulty index: 3728k/33842k
INFO[12-20|02:08:25.230] [fillind_db_from_snapshots] Total difficulty index: 5737k/33842k
INFO[12-20|02:08:45.230] [fillind_db_from_snapshots] Total difficulty index: 7687k/33842k
INFO[12-20|02:09:05.230] [fillind_db_from_snapshots] Total difficulty index: 10447k/33842k
INFO[12-20|02:09:25.230] [fillind_db_from_snapshots] Total difficulty index: 12479k/33842k
INFO[12-20|02:09:48.771] [fillind_db_from_snapshots] Total difficulty index: 14913k/33842k
INFO[12-20|02:10:05.230] [fillind_db_from_snapshots] Total difficulty index: 17054k/33842k
INFO[12-20|02:10:25.230] [fillind_db_from_snapshots] Total difficulty index: 18955k/33842k
INFO[12-20|02:10:45.230] [fillind_db_from_snapshots] Total difficulty index: 21861k/33842k
INFO[12-20|02:11:05.230] [fillind_db_from_snapshots] Total difficulty index: 23844k/33842k
INFO[12-20|02:11:25.827] [fillind_db_from_snapshots] Total difficulty index: 26097k/33842k
INFO[12-20|02:11:45.230] [fillind_db_from_snapshots] Total difficulty index: 28888k/33842k
INFO[12-20|02:11:46.827] [parlia] snapshots build, gather headers block=29000000
INFO[12-20|02:11:47.620] [parlia] snapshots build, recover from headers block=29000000
EROR[12-20|02:11:49.460] invalid validators bytes

**Comment by zformular** [comment]
I run with erigon_x64_v1.1.9--Build20231205 to catch up the blocks, and switch back to v1.1.10
it works , i don't know why
