### ISSUE TITLE
7/15 Execution step error: could not apply tx 0 from block 30000000

### ISSUE THREAD

**Issue by czarly** [node-real/bsc-erigon#286]
please let me reopen this. 

I'm trying to to sync a full node and synced with 1.10-devel until I reached the error from the title "could not apply tx 0 from block 30000000"

Then I upgraded to v1.11 and did the header reset

`integration stage_headers --reset --chain=bsc --datadir=..pathtostorage..`

and got stuck with endless repetition of the following line

```
[INFO] [01-07|02:40:53.795] [snapshots] Verifying                    progress=99.11%
[INFO] [01-07|02:41:05.416] [snapshots] Blocks Stat                  blocks=30500k indices=30500k alloc=4.2GB sys=7.9GB
[INFO] [01-07|02:41:05.417] [1/15 Snapshots] DONE                    in=3m11.626203928s
...
[INFO] [01-07|03:39:44.077] [p2p] GoodPeers                          eth66=185 eth67=8 eth68=39
[INFO] [01-07|03:41:44.076] [p2p] GoodPeers                          eth67=8 eth68=40 eth66=185
[INFO] [01-07|03:43:44.076] [p2p] GoodPeers                          eth68=40 eth66=185 eth67=8
```

I tried to delete and redownload the snapshots with the same result. 

my command line:

`erigon --chain=bsc --nat=stun --sentry.drop-useless-peers --http --http.addr=0.0.0.0 --http.port=8545 --http.compression --http.vhosts='*' --http.corsdomain='*' --http.api=eth,debug,net,trace,web3,erigon,bor --ws --ws.compression --rpc.gascap=300000000 --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --bodies.cache=5G --rpc.batch.limit=200000 --db.pagesize=16k --batchSize=2048MB --port=54993 --p2p.protocol=66 --p2p.protocol 67 --p2p.protocol 68 --p2p.allowed-ports 53931 --p2p.allowed-ports 22185 --p2p.allowed-ports 9521 --datadir=/datadir --ethash.dagdir=/datadir/ethash --rpc.returndata.limit=1100000 --snapshots=true --downloader.verify --torrent.port 25703 --torrent.download.rate 1000mb --torrent.upload.rate 10mb --prune.h.older=128 --prune.r.older=128 --prune.t.older=128 --prune.c.older=128`

_Originally posted by @czarly in https://github.com/node-real/bsc-erigon/issues/226#issuecomment-1879928154_

**Comment by czarly** [comment]
How do I know that 1.1.12 will work? can I just sync over what I have with the new version? I started 3 times since October each time with a version that was supposed to work. How do I know that it will work this time? The experiment piled up at least $1000 in cost already. Are there snapshots for full nodes somewhere?

**Comment by czarly** [comment]
those snapshots are for archive nodes. I want a full node. thus I tried to sync from genesis because I can only find snapshots for4 archive nodes and I think they can not be pruned after the fact. I tried to prune them but was not successful.

**Comment by lilcryptopump** [comment]
Same. @czarly please post solution if you will find it

**Comment by czarly** [comment]
yep I did and I now realised that I'm actually stuck at block 30499999 not 29999999 anymore. need to close this issue.
