### ISSUE TITLE
Weired Logs

### ISSUE THREAD

**Issue by gautamjha2002** [node-real/bsc-erigon#290]
I am running binance archive node with bsc-erigon 

**Issue 1 :-** Only step 2/15 and step 7/15 is executing Not others. 

`Jan 15 04:59:30 square-owl erigon[140886]: [INFO] [01-15|04:59:30.939] Tables                                   PlainState=285.7GB AccountChangeSet=655.6GB StorageChangeSet=1.5TB BlockTransaction=55.9GB TransactionLog=2.7TB FreeList=186.4MB ReclaimableSpace=745.6GB
Jan 15 04:59:30 square-owl erigon[140886]: [WARN] [01-15|04:59:30.940] [snapshots] retire blocks                err="DumpBlocks: DumpHeaders: header missed in db: block_num=34000000,  hash=f2b5035c81e74c3ec2de5c001fc031f4656be635e73d02b2ee7de8e5117ea061" fromBlock=34000000 toBlock=34500000
Jan 15 04:59:30 square-owl erigon[140886]: [INFO] [01-15|04:59:30.980] [2/15 Headers] Waiting for headers...    from=35257100
Jan 15 04:59:33 square-owl erigon[140886]: [INFO] [01-15|04:59:33.121] [2/15 Headers] Processed                 highest inserted=35257101 age=0
Jan 15 04:59:33 square-owl erigon[140886]: [INFO] [01-15|04:59:33.296] [7/15 Execution] Completed on            block=35257101
Jan 15 04:59:33 square-owl erigon[140886]: [INFO] [01-15|04:59:33.711] RPC Daemon notified of new headers       from=35257100 to=35257101 hash=0x7e38728bf34e7e8abdd87999ab91f46c0a5608eedb8cc89bb34c377905617820 header sending=15.075µs log sending=559ns
Jan 15 04:59:33 square-owl erigon[140886]: [INFO] [01-15|04:59:33.711] Commit cycle                             in=69.400769ms
Jan 15 04:59:33 square-owl erigon[140886]: [INFO] [01-15|04:59:33.711] Timings (slower than 50ms)               Headers=2.14s Execution=97ms HashState=64ms IntermediateHashes=115ms`

**Issue 2 :-**  There is a warning in logs which says **DumpBlocks: DumpHeaders: header missed in db: block_num=34000000,  hash=f2b5035c81e74c3ec2de5c001fc031f4656be635e73d02b2ee7de8e5117ea061" fromBlock=34000000 toBlock=34500000** How to solve this ?

In issue number 1 above I am not confirm if it's an error or bsc-erigon works likes this only? so please confirm

My logs :- 

![image](https://github.com/node-real/bsc-erigon/assets/98412293/26bf1edc-2cd0-413f-83a5-3b033395d96f)

**Comment by frangrech** [comment]
Hey @blxdyx, we were having the same issue. Tried running the integration cmd above but we are now getting:
`[2/15 Headers] No block headers to write in this log period block number=34537946`
Any suggestions?
