### ISSUE TITLE
FAQ: Solution For Common Issues

### ISSUE THREAD

**Issue by calmbeing** [node-real/bsc-erigon#41]
# Rationale
For some common issue encountered, such as the follows:
- `No block header/body write`.
- Body download speed is slow
- `Database is too large for current system`
# Solution

Please try to specify these flags in the command line for starting node:
- `--p2p.protocol=67`
- `--db.pagesize=16k`
- `--db.size.limit=[500GB,(default: "7TB") ]`

Also, for some cases that now work especially in reboot scenario, it'll help to unwind some blocks:

1. Stop erigon node
2. run `make integration`
3. run `./build/bin/integration stage_exec --datadir ./data/ --chain bsc --unwind 10`
4. Start erigon node

# FAQs
### Q2: Any suggested start up command line?
Here is our command line to start on BSC Mainnet, you can use on your need.
> Note: we have plenty SSD disk storage to support archive node, which is 14TB, so we set `--db.pagesize=16k` for fast DB performance. You may configure it according to your device setting. 
```
 nohup ./build/bin/erigon  --txpool.disable --p2p.protocol=66,67 --metrics.addr=0.0.0.0 --log.console.verbosity=dbug --db.pagesize=16k --datadir ./data --private.api.addr=localhost:9090 --chain=bsc --metrics --log.dir.path ./log &
```
### Q3: OOM Crash?
Try not specify the body cache and batch size: `--bodies.cache=214748364800 --batchSize=4096M`.
These 2 flags will bring heavy to RAM caches. Similar issue: https://github.com/node-real/bsc-erigon/issues/39

### Q5:  Log with "DumpBlocks: DumpHeaders: header missed in db:"
It won't affect sync,  stop erigon and ./integration stage_headers --reset --chain=bsc --datadir=yourdata will fix.

**Comment by blxdyx** [comment]
No block header write. you could try this:
```
integration state_stages --unwind=20 --chain=bsc --datadir=/path
integration stage_headers --unwind=20 --chain=bsc --datadir=/path
```

**Comment by Denis-score** [comment]
Since yesterday, it's still complicated to be live sync with erigon. I always have 50-100 blocks of delay. Anyone have an idea ?

**Comment by harveyff** [comment]
> Since yesterday, it's still complicated to be live sync with erigon. I always have 50-100 blocks of delay. Anyone have an idea ?

One week ago, I was also behind by dozens of blocks. Since one week ago, I have been behind by 2000 blocks, and it is getting slower and slower. Without any ideas, it can no longer provide services for the production environment.

**Comment by zhy827827** [comment]
How to fix crash  issues when  debug_traceBlockByNumber

` RPC method debug_traceBlockByNumber crashed: runtime error: index out of range [-1]
erigon[3076643]: [service.go:217 panic.go:838 panic.go:89 call.go:176 interpreter.go:234 interpreter.go:262 evm.go:65 evm.go:403 evm.go:451 state_transition.go:395 state_transition.go:186 tracing.go:195 tracing.go:140 tracing.go:32 value.go:556 value.go:339 service.go:222 handler.go:511 handler.go:444 handler.go:392 handler.go:223 handler.go:316 asm_amd64.s:1571]`

**Comment by du5** [comment]
`214748364800 bytes = 200 gigabytes` 

I think this parameter can be set to about 4G. There is no comparison with physical memory in the code. 200G seems to easily exceed the user's memory size.

**Comment by du5** [comment]
If you want to speed up the startup of erigon3 archive node, please refer to Using multithreaded downloading


https://github.com/48Club/bsc-snapshots/blob/main/README.md#erigon-archive-node

```bash 
# install dependencies
sudo apt-get install -y aria2 curl jq
# download snapshot
curl -skL https://bit.ly/3znHXPc | bash
mv snapshots /data/erigon
# start erigon
erigon3 --prune.mode=archive --chain=bsc --datadir=/data/erigon ...
```
