### ISSUE TITLE
v1.0.4 fresh sync fails

### ISSUE THREAD

**Issue by CRossel87a** [node-real/bsc-erigon#55]
Hi,

Decided to spin up a fresh bsc-erigon node today without using snapshots. Using v1.0.4 binary

At around 668.1GB chaindata size this error occured:

WARN[05-05|21:18:04.418] Index file has timestamp before segment file, will be recreated segfile=/root/dev/bsc-erigon/bsc-erigon-1.0.4/build/bin/node/snapshots/v1-021500-022000-headers.seg segtime=2023-05-05T21:18:04+0200 idxfile=v1-021500-022000-headers.idx idxtime=2023-05-05T20:49:58+0200
WARN[05-05|21:18:04.420] Index file has timestamp before segment file, will be recreated segfile=/root/dev/bsc-erigon/bsc-erigon-1.0.4/build/bin/node/snapshots/v1-022000-022500-headers.seg segtime=2023-05-05T21:10:16+0200 idxfile=v1-022000-022500-headers.idx idxtime=2023-05-05T19:30:22+0200
WARN[05-05|21:18:04.420] Index file has timestamp before segment file, will be recreated segfile=/root/dev/bsc-erigon/bsc-erigon-1.0.4/build/bin/node/snapshots/v1-022500-023000-headers.seg segtime=2023-05-05T21:11:16+0200 idxfile=v1-022500-023000-headers.idx idxtime=2023-05-05T12:15:07+0200
WARN[05-05|21:18:04.496] Index file has timestamp before segment file, will be recreated segfile=/root/dev/bsc-erigon/bsc-erigon-1.0.4/build/bin/node/snapshots/v1-022000-022500-bodies.seg segtime=2023-05-05T21:10:17+0200 idxfile=v1-022000-022500-bodies.idx idxtime=2023-05-05T20:49:57+0200
WARN[05-05|21:18:04.497] Index file has timestamp before segment file, will be recreated segfile=/root/dev/bsc-erigon/bsc-erigon-1.0.4/build/bin/node/snapshots/v1-022500-023000-bodies.seg segtime=2023-05-05T21:09:11+0200 idxfile=v1-022500-023000-bodies.idx idxtime=2023-05-05T20:49:57+0200
EROR[05-05|21:18:06.436] Staged Sync                              err="[1/15 Snapshots] BuildMissedIndices: HeadersIdx: at=v1-021500-022000-headers.seg, file: v1-021500-022000-headers.seg, runtime error: slice bounds out of range [:-1], [decompress.go:532 panic.go:884 panic.go:139 decompress.go:553 block_snapshots.go:1899 block_snapshots.go:1823 block_snapshots.go:869 block_snapshots.go:912 errgroup.go:75 asm_amd64.s:1594], [block_snapshots.go:1806 panic.go:884 decompress.go:532 panic.go:884 panic.go:139 decompress.go:553 block_snapshots.go:1899 block_snapshots.go:1823 block_snapshots.go:869 block_snapshots.go:912 errgroup.go:75 asm_amd64.s:1594]"
INFO[05-05|21:18:06.940] [1/15 Snapshots] Fetching torrent files metadata
INFO[05-05|21:18:26.945] [1/15 Snapshots] download                progress="98.71% 659.5GB/668.1GB" download-time-left=0hrs:15m total-download-time=20s download=9.2MB/s upload=0B/s
INFO[05-05|21:18:26.946] [1/15 Snapshots] download                peers=8 connections=10 files=170 alloc=4.4GB sys=6.6GB
INFO[05-05|21:18:46.944] [1/15 Snapshots] download                progress="98.77% 659.9GB/668.1GB" download-time-left=0hrs:6m total-download-time=40s download=21.4MB/s upload=0B/s
INFO[05-05|21:18:46.944] [1/15 Snapshots] download                peers=7 connections=8 files=170 alloc=2.7GB sys=6.6GB
INFO[05-05|21:18:54.998] [txpool] stat                            pending=1 baseFee=0 queued=184 alloc=3.0GB sys=6.6GB
INFO[05-05|21:19:06.945] [1/15 Snapshots] download                progress="98.84% 660.4GB/668.1GB" download-time-left=0hrs:5m total-download-time=1m0s download=24.0MB/s upload=0B/s
INFO[05-05|21:19:06.945] [1/15 Snapshots] download                peers=9 connections=10 files=170 alloc=3.3GB sys=6.6GB

It will spin like this in circles, deleting and re-downloading only to fail. 

Unwinding execution by 10 blocks did not help

Node specs:
2TB SSD,
64gb ram,
14 cores
Netcup root dedicated server

**Comment by blxdyx** [comment]
try remove the v1-021500-022000-headers.seg.idx file in <your_datadir>/snapshots folder and restart

**Comment by CRossel87a** [comment]
New problem. Tried unwind on stages and headers by 10. Its stuck on this transaction:

![image](https://user-images.githubusercontent.com/110127027/236679272-465d8733-c2d3-4364-81b3-f9fecd0469eb.png)

**Comment by blxdyx** [comment]
try this
```
./build/bin/integration state_stages --datadir=<your_datadir> --unwind=1000 --integrity.fast=false --chain=bsc
./build/bin/integration stage_bodies --datadir=<your_datadir> --unwind=1000 --chain=bsc
./build/bin/integration stage_headers --datadir=<your_datadir> --unwind=1000 --chain=bsc
```

**Comment by CRossel87a** [comment]
> try this
> 
> ```
> ./build/bin/integration state_stages --datadir=<your_datadir> --unwind=1000 --integrity.fast=false --chain=bsc
> ./build/bin/integration stage_bodies --datadir=<your_datadir> --unwind=1000 --chain=bsc
> ./build/bin/integration stage_headers --datadir=<your_datadir> --unwind=1000 --chain=bsc
> ```

Hi, thank you for the reply. In addition to 1000 I also tried 10000, but it keeps coming back to:
EROR[05-08|08:35:05.680] Staged Sync                              err="[5/15 Bodies] WriteRawBodyIfNotExists: WriteRawTransactions: txId=4129961969, baseTxId=4129961969, bucket: BlockTransaction, mdbx_cursor_put: MDBX_EKEYMISMATCH: The given key value is mismatched to the current cursor position"

**Comment by CRossel87a** [comment]
Do you see an issue?
![image](https://user-images.githubusercontent.com/110127027/236766663-4f2bc1d3-52b1-4019-99fb-1fbbf813c2c5.png)

**Comment by blxdyx** [comment]
Try to remove /snapshots/db folder. 
I try to reproduce this problem, but it's seem ok.

**Comment by CRossel87a** [comment]
> Must to remove /snapshots/db folder when you remove .idx file. I forget this. I try to reproduce this problem, but it's seem ok. It is a better suggestion to download the latest [snapshot](https://github.com/bnb-chain/bsc-snapshots), or spin up a fresh bsc-erigon node.

This problem is occuring during a fresh spin up of bsc-erigon. I am attempting a final third wipe & reset now

**Comment by blxdyx** [comment]
I means start sync from a new node, it appears there is a data inconsistency issue.
Sometimes it can work once you unwind, like [this](https://github.com/ledgerwatch/erigon/issues/5385)

**Comment by CRossel87a** [comment]
@blxdyx No errors now atleast, but there does seem to be peer issues. Here connected to 989 peers and still seemingly stuck. this is from running a fresh sync up

![image](https://github.com/node-real/bsc-erigon/assets/110127027/c35d1704-98be-4104-b9ed-8c4c94d60c83)

**Comment by blxdyx** [comment]
It seems normal. Please show more info if it's stuck.

**Comment by CRossel87a** [comment]
@blxdyx I updated to devel branch since 1.0.4 didn't go anywhere. I have supplied the node with very many static peers and bootnodes. The fresh sync has been running for about 6-7 days but fails catching up: 
![image](https://github.com/node-real/bsc-erigon/assets/110127027/05a11594-6054-462b-a465-af14afacca31)

**Comment by CRossel87a** [comment]
Chain-data is about 800GB at this point and seems to be almost caught up, but just doesn't hook on

**Comment by setunapo** [comment]
closed, followed in: https://github.com/node-real/bsc-erigon/issues/55

**Comment by BillyTsangGC** [comment]
> Must to remove /snapshots/db folder when you remove .idx file. I forget this. I try to reproduce this problem, but it's seem ok. It is a better suggestion to download the latest [snapshot](https://github.com/bnb-chain/bsc-snapshots), or spin up a fresh bsc-erigon node.

it works for me, thanks
