### ISSUE TITLE
v1.0.4 sync failure for bsc mainnet at block 28035800

### ISSUE THREAD

**Issue by tsutsu** [node-real/bsc-erigon#60]
(I know running v1.0.3+ is not currently recommended for bsc mainnet; I was running a v1.0.4 node on bsc mainnet as a test, to find sync bugs like this one.)

```
[INFO] [05-08|17:13:53.950] [5/15 Bodies] Processed                  highest=28036306
[INFO] [05-08|17:13:53.950] [6/15 Senders] Started                   from=28035799 to=28036306
[INFO] [05-08|17:13:54.263] [7/15 Execution] Blocks execution        from=28035799 to=28036306
[WARN] [05-08|17:13:54.321] [7/15 Execution] Execution failed        block=28035800 hash=0xad1e9a9a2c1372b40a5a0e65209347edc01896a7830cfc87ad5b029266fdea58 err="mismatching validator list on epoch block"
[INFO] [05-08|17:13:54.321] UnwindTo                                 block=28035799 bad_block_hash=0xad1e9a9a2c1372b40a5a0e65209347edc01896a7830cfc87ad5b029266fdea58
[INFO] [05-08|17:13:54.321] [7/15 Execution] Completed on            block=28035799
[INFO] [05-08|17:13:54.388] [2/15 Headers] Waiting for headers...    from=28035799
```

Visually, this is the same error as v1.0.3 had for chapel. Presumably has a different cause, given that the luban fork is inactive for bsc mainnet.

Epoch block https://bscscan.com/block/28035800 doesn't look any different than the previous epoch block https://bscscan.com/block/28035600, so I'm not sure what would trigger this for 28035800 but not 28035600.

It is likely that the not-inLuban consensus logic in v1.0.3+ is not functionally identical to the consensus logic in ≤v1.0.2.

Downgrading to v1.0.2 allows sync to proceed from 28035799 without any need for unwinding, so it seems that the validator state was not corrupted by some block between 28035600 and 28035799, but rather the failure is limited to the processing of 28035800.

**Comment by calmbeing** [comment]
@tsutsu Can you confirm your erigon version? And also please make sure unwind some blocks if you switch from v1.0.3 to v1.0.4. Because we didn't encounter this error for this height in our machine.
