### ISSUE TITLE
Syncing at execution layer is too slow 

### ISSUE THREAD

**Issue by farhan-systango** [node-real/bsc-erigon#66]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Erigon's discord](https://github.com/ledgerwatch/erigon#erigon-discord-server).

Hi Team,

I have started the node using snapshots & it syncs really slow only 7-8 blk/sec. Here are the hardware details for more information:
Machine SKU: Standard_L16
vCPU: 16
RAM: 128GB

I am running the service with the following command: 
`exec erigon --chain bsc --snapshots=true --db.pagesize=16k --datadir=/bnb-backup/data --txpool.disable --rpc.batch.concurrency=1500 --rpc.batch.limit=1500 --torrent.upload.rate=512mb --torrent.download.rate=512mb --http.addr=0.0.0.0 --http.port=8545 --rpc.returndata.limit=1024000 --p2p.protocol=66`

that way it takes infinite time to sync with the bsc mainnet.

![image](https://github.com/node-real/bsc-erigon/assets/104916084/b78771b7-180a-4ff9-857a-b53c458f95dc)

**Comment by seonggwonyoon** [comment]
Same on AWS (is4gen.4xlarge)

**Comment by zhy827827** [comment]
![Uploading image.png…]()
![1684309559312](https://github.com/node-real/bsc-erigon/assets/15209848/6074246f-3729-46fc-92b7-ff9b214d7a3c)

**Comment by qinglin89** [comment]
Ref: #8

**Comment by setunapo** [comment]
I am afraid it is a known performance issue of Erigon, currently ~10 blk/sec sounds is not that bad.
We will keep the performance improve task in our long term support plan, close this issue right now.
