### ISSUE TITLE
BSC Testnet stuck v1.0.4

### ISSUE THREAD

**Issue by mateipopp** [node-real/bsc-erigon#71]
#### System information

Erigon version: `./erigon --version`

erigon version 2.43.0-dev-7bfcc2bb
OS & Version: Windows/Linux/OSX
Ubuntu22.04
Commit hash: 
7bfcc2bb226592ef7ea11211e534b4e7ab75054c
Erigon Command (with flags/config):
/usr/local/bin/erigon --chain=chapel  --datadir=/node/data --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --private.api.addr=0.0.0.0:9090 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061 --torrent.download.rate=1000mb --bodies.cache=214748364800 --batchSize=4096M --p2p.protocol=66 --db.size.limit=1800GB --http=false 

Chain/Network: 
Chapel

````
May 12 09:18:58 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:18:58.872] [2/15 Headers] Waiting for headers...    from=29614555
May 12 09:18:59 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:18:59.366] [parlia] snapshots build, gather headers block=29600000
May 12 09:18:59 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:18:59.545] New txs subscriber joined
May 12 09:18:59 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:18:59.546] new subscription to newHeaders established
May 12 09:18:59 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:18:59.773] [txpool] Started
May 12 09:19:01 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:19:01.833] local tx propagated                      tx_hash=f2f37c3bcf91e0a766cd16a900522fbad0c7c47de287ff2f6226f65299f2d4d2 announced to peers=3 broadcast to peers=1 baseFee=0
May 12 09:19:20 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:19:20.345] local tx propagated                      tx_hash=d4f4f159b12f7639a07d364cf1c176df1fb03380d5eb1f086ed6b828d3c41ae4 announced to peers=3 broadcast to peers=1 baseFee=0
May 12 09:19:58 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:19:58.858] [txpool] stat                            pending=10000 baseFee=0 queued=29915 alloc=241.6MB sys=277.0MB
May 12 09:20:45 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:20:45.468] local tx propagated                      tx_hash=c4aa0629eb35a60458200f4ec3808d720d929171206b3da574f587349b203a54 announced to peers=5 broadcast to peers=2 baseFee=0
May 12 09:20:51 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:20:51.566] local tx propagated                      tx_hash=ff2dcc715ca429e13b639c49135a3b338854586f2641fbd04564565ef4291cdf announced to peers=5 broadcast to peers=2 baseFee=0
May 12 09:20:58 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:20:58.240] [p2p] GoodPeers                          eth66=5
May 12 09:20:58 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:20:58.885] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=293.0MB sys=331.5MB
May 12 09:20:59 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:20:59.609] local tx propagated                      tx_hash=98f4632116188036891d9e9ef231e2733f8571f4f1a6a973f003e74e21d4594c announced to peers=4 broadcast to peers=2 baseFee=0
May 12 09:21:58 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:21:58.858] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=236.6MB sys=332.4MB
May 12 09:22:05 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:22:05.772] local tx propagated                      tx_hash=319f07cf8bd43f2654e07ff76472e44e9769723c14a74856e02c5626e924c6ef announced to peers=4 broadcast to peers=2 baseFee=0
May 12 09:22:47 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:22:47.127] local tx propagated                      tx_hash=7106493a14acca31e146f7e8852333b06912cb8aa1390a8e23432c5dacb4738c announced to peers=4 broadcast to peers=2 baseFee=0
May 12 09:22:47 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:22:47.397] local tx propagated                      tx_hash=7106493a14acca31e146f7e8852333b06912cb8aa1390a8e23432c5dacb4738c announced to peers=4 broadcast to peers=2 baseFee=0
May 12 09:22:47 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:22:47.397] local tx propagated                      tx_hash=a30722dfac82d249fa8481aea50f11f7898f88e36446cd1a89914e8bfdea5b58 announced to peers=4 broadcast to peers=2 baseFee=0
May 12 09:22:58 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:22:58.240] [p2p] GoodPeers                          eth66=5
May 12 09:22:58 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:22:58.887] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=299.2MB sys=340.6MB
May 12 09:23:58 bsc-archive-testnet-0-eu erigon[870216]: [INFO] [05-12|09:23:58.859] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=227.3MB sys=344.6MB
````
Updated to the latest version v1.0.4, worked for 3 days, and after that, the node remained stuck with no errors.
We've already tried restarting the node multiple times and even attempted to unwind it, but no luck.

**Comment by calmbeing** [comment]
Can you disable these two flags and try to reboot the node?  `--bodies.cache=214748364800 --batchSize=4096M`

**Comment by mateipopp** [comment]
@calmbeing same issue. 
May 12 11:26:24 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:26:24.101] [2/15 Headers] Waiting for headers...    from=29614555
May 12 11:26:24 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:26:24.457] [parlia] snapshots build, gather headers block=29600000
May 12 11:26:24 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:26:24.745] New txs subscriber joined
May 12 11:26:24 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:26:24.746] new subscription to newHeaders established
May 12 11:26:25 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:26:25.011] [txpool] Started
May 12 11:27:24 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:27:24.086] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=251.1MB sys=290.2MB
May 12 11:27:31 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:27:31.351] local tx propagated                      tx_hash=311cf200c97344acdeaaa5f9a776ab06aca26fee6940e05b6cb124b61fa3db43 announced to peers=3 broadcast to peers=1 baseFee=0
May 12 11:28:23 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:28:23.479] [p2p] GoodPeers                          eth66=4
May 12 11:28:24 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:28:24.113] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=311.8MB sys=353.3MB
May 12 11:29:24 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:29:24.087] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=296.5MB sys=370.3MB
May 12 11:30:23 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:30:23.479] [p2p] GoodPeers                          eth66=8
May 12 11:30:24 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:30:24.099] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=209.3MB sys=370.4MB
May 12 11:31:24 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:31:24.087] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=253.6MB sys=386.4MB
May 12 11:32:23 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:32:23.479] [p2p] GoodPeers                          eth66=9
May 12 11:32:24 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:32:24.105] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=260.6MB sys=386.4MB
May 12 11:33:24 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:33:24.086] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=264.9MB sys=386.4MB
May 12 11:33:53 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:33:53.065] local tx propagated                      tx_hash=21ef7ab38b00e6757b3a9a8af423feccbb2e9e716253478d151e8fa68ca6a7a3 announced to peers=10 broadcast to peers=3 baseFee=0
May 12 11:34:23 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:34:23.479] [p2p] GoodPeers                          eth66=10
May 12 11:34:24 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:34:24.099] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=207.0MB sys=386.4MB
May 12 11:35:24 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:35:24.088] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=290.4MB sys=390.4MB
May 12 11:36:23 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:36:23.479] [p2p] GoodPeers                          eth66=10
May 12 11:36:24 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:36:24.105] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=183.3MB sys=390.4MB
May 12 11:37:24 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:37:24.088] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=307.4MB sys=390.4MB
May 12 11:38:23 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:38:23.479] [p2p] GoodPeers                          eth66=11
May 12 11:38:24 bsc-archive-testnet-0-eu erigon[870519]: [INFO] [05-12|11:38:24.100] [txpool] stat                            pending=10000 baseFee=0 queued=30000 alloc=290.7MB sys=390.4MB

**Comment by calmbeing** [comment]
This issue was solved by this commit
https://github.com/node-real/bsc-erigon/commit/98a5f982eccee6ebdc038874457743922547790a

**Comment by mateipopp** [comment]
Updated the nodes, so far nodes are working properly.
