### ISSUE TITLE
Command line parameter suggestion to run a stable archival node

### ISSUE THREAD

**Issue by breezytm** [node-real/bsc-erigon#72]
Hi, Just curious to see if anyone would be willing to share their command line if they are running a stable archival node. My node is constantly trailing behind and I find myself frequently rebooting it to stay synced. 

My current setup 
Docker image ``ghcr.io/node-real/bsc-erigon:1.0.3``

```    
command:
      - --chain=bsc
      - --datadir=/root/.local/share/erigon
      - --port=30303
      - --private.api.addr=0.0.0.0:9090
      - --torrent.port=42069
      - --torrent.download.rate=1000mb
      - --torrent.download.slots=6
      - --p2p.protocol=66
      - --downloader.verify
      - --batchSize=512M
      - --etl.bufferSize=512M
      - --db.pagesize=16k
      - --healthcheck
      - --log.console.verbosity=info

**Comment by icculp** [comment]
You might want to try adding the flag --db.size.limit=10000GB or so. It has a default of 7tb and I do believe performance is degraded as it approaches that limit

**Comment by icculp** [comment]
![image](https://github.com/node-real/bsc-erigon/assets/57159226/2ac4963e-8a86-4892-b801-9af24e97e433)

**Comment by breezytm** [comment]
I am in the process of redeploying my instances but two people confirmed removing `--batchSize`, `--etl.bufferSize` and `--bodies.cache` have stabilized their environment for mainnet. @icculp try and confirm.

**Comment by icculp** [comment]
On v1.0.5 it's still acting up using the existing data which was a fresh unpack of the main snapshot which tried v1.0.2, v1.0.3, and v1.0.4. First time after on v.1.0.5 was repeating stage 5 over and over; restarted and now it's just stuck on `[5/15 Bodies] No block bodies to write in this log period block number=28266663`. Trying to unpack the snapshot again and start fresh on that and see

**Comment by zhy827827** [comment]
Our nodes often lag behind blocks,and restart erigon  then erigon sync started again. 
the issuse logs:
 [5/15 Bodies] No block bodies to write in this log period block

`/home/ubuntu/erigon/build/bin/erigon --datadir=/opt/bscdata/erigon --chain=bsc  --db.pagesize=16k  --torrent.download.rate=512mb --torrent.upload.rate=10mb --private.api.addr=127.0.0.1:9090 --http.api eth,erigon,web3,net,debug,trace,txpool --ws --ws.compression --http.addr=0.0.0.0 --http.corsdomain '*' --http.vhosts '*' --p2p.protocol=66,68 --torrent.download.slots 6 --bodies.cache 6341225472`

**Comment by setunapo** [comment]
pls refer: https://github.com/node-real/bsc-erigon#faq
