### ISSUE TITLE
code of address 0x0000000000000000000000000000000000001000 is not correct after Luban hardfork

### ISSUE THREAD

**Issue by rekyyang** [node-real/bsc-erigon#73]
#### System information

Erigon version: `./erigon --version`

OS & Version: Windows/Linux/OSX

Commit hash: 

Erigon Command (with flags/config):

Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network:  Chapel

#### Expected behaviour

the code of address 0x0000000000000000000000000000000000001000 has changed after Luban hardfork (0x1bf01ca), but erigon did not update the code. but if getCode from "latest", the result is correct.

request：
`{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "eth_getCode",
    "params": [
        "0x0000000000000000000000000000000000001000",
        "0x1bf01cc"
    ]
}`

expected：

`{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "0x60806040526004361061046c57600.........."
}`

#### Actual behaviour

`{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "0x60806040526004361061040557..........."
}`

#### Backtrace

````
[backtrace]
````

**Comment by calmbeing** [comment]
Should be fixed by this pr https://github.com/node-real/bsc-erigon/pull/146/files
