### ISSUE TITLE
1.0.4 Spins around block 26999999

### ISSUE THREAD

**Issue by CRossel87a** [node-real/bsc-erigon#76]
Hi,

I have now run this node for well over a week, and I've noticed a repeating behavior of writing block bodies around block 26999999. It will work itself down the remaining=1199715, then spin backup again to repeat the work. It has done this 3-4 times now

![image](https://github.com/node-real/bsc-erigon/assets/110127027/9e929b3e-4669-4143-8711-d9918744934a)

**Comment by mhd-alawieh** [comment]
Same behavior here with latest version v1.0.8

**Comment by setunapo** [comment]
do you still get the problem?

**Comment by CRossel87a** [comment]
> do you still get the problem?

I just started spinning up a fresh using v1.1.0, will get back to you. It does seem to be making good progress. Using the drop useless sentries flag
![image](https://github.com/node-real/bsc-erigon/assets/110127027/b12f424c-0863-4fec-bc60-707683463ddf)

**Comment by CRossel87a** [comment]
> Hi, any update? otherwise, we may close this issue.

Hi, it's still working on the sync, but it seems to be fine thank you. I think it is safe to close.
