### ISSUE TITLE
wanted: to provide a snapshot of BSC testnet

### ISSUE THREAD

**Issue by setunapo** [node-real/bsc-erigon#86]
# Rationale
The data volume of BSC Testnet is becoming more and more large, it could takes days for people to sync from genesis.
It would be better to provide one in: https://github.com/bnb-chain/bsc-snapshots#erigon-bsc-snapshot

# Implementation
No need to update frequently, quarterly update could be ok IMO

**Comment by icculp** [comment]
How large is the testnet chain now? Growth rate?

**Comment by setunapo** [comment]
@icculp @Zorato we were stuck by some issues to sync testnet from genesis, but now they are solved. And we are updating the snapshot of testnet.
The latest size for bsc testnet is around 550GB (Jun-20-2023).
For the growth rate, we have no data yet, we can calculate it next time we update the snapshot, but the time for next update is not determined yet, since it is not that necessary to update it frequently for testnet.

**Comment by Zorato** [comment]
@setunapo Is there any link where I can download testnet snapshot?

**Comment by setunapo** [comment]
@Zorato we will upload it soon, need to find a useable s3 server.

**Comment by calmbeing** [comment]
@Zorato  Supported, please check out https://github.com/bnb-chain/bsc-snapshots/pull/276/files
