### ISSUE TITLE
Consensus snapshot state corruption since v1.0.7 on node restart at certain heights

### ISSUE THREAD

**Issue by tsutsu** [node-real/bsc-erigon#95]
I've been running a `bsc-mainnet` node on v1.0.8, with a watchdog to restart it if it hits "no block bodies...", and it's been mostly stable; but every once in a while — seemingly at random (until I figured out the pattern) — it would come back up after a watchdog restart in a corrupted state, where execution would fail with `mismatching validator list on epoch block`.

Fixing this when it happens, requires stopping the node and unwinding `state_stages` by one block.

After seeing this a few times, I eventually noticed that this happens when, after a restart, the execution stage starts at a block height ending in `{1,3,5,7,9}99` (i.e. one block before a consensus snapshot.)

I assume that the current logic is written to expect that some in-memory state in parlia will already be available *from* block ...98, to be used *during* execution of block ...99, to set up the snapshot *for* block ...00. Where if execution starts at block ...99, then that state won't be available, so the snapshot for block ...00 will end up calculated incorrectly.

**Comment by setunapo** [comment]
checking.

**Comment by alexlee85** [comment]
same problem here

**Comment by calmbeing** [comment]
Should be fixed by these update:
https://github.com/node-real/bsc-erigon/pull/102
https://github.com/node-real/bsc-erigon/pull/111/files#diff-afffa34063d33db53677de5b49f3f3fcced5b5c65889f1d27d4d92eedddd1e99R876

**Comment by calmbeing** [comment]
Please reopen if occur again
