### ISSUE TITLE
why curl eth_blockNumber result 0x0

### ISSUE THREAD

**Issue by lk479o000** [node-real/bsc-erigon#96]
nohup ./build/bin/erigon --chain=bsc --datadir=/erigon_chain  --http=true --http.addr=0.0.0.0 --http.port=9001 --http.api=eth,erigon,web3,net,debug,trace,txpool --ws --torrent.port=42069 --torrent.download.rate=32mb --authrpc.port=8551 --private.api.addr=127.0.0.1:9090 --db.pagesize=16kb --snapshots=true --rpc.batch.limit=10000  --prune=htc --prune.h.older=90000 --prune.t.older=90000 --prune.c.older=90000 &

curl -s -H "Content-Type:application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' 0.0.0.0:9001

{"jsonrpc":"2.0","id":1,"result":"0x0"}

Synchronized to the latest block:
[INFO] [05-22|02:57:18.958] [2/15 Headers] Wrote block headers       number=28421656 blk/second=9.600 alloc=2.6GB sys=3.3GB
[INFO] [05-22|02:57:38.958] [2/15 Headers] No block headers to write in this log period block number=28421656
[INFO] [05-22|02:57:58.496] [p2p] GoodPeers                          eth66=31 eth68=1
[INFO] [05-22|02:57:58.905] [txpool] stat                            pending=1 baseFee=0 queued=14 alloc=2.7GB sys=3.3GB
[INFO] [05-22|02:57:58.958] [2/15 Headers] No block headers to write in this log period block number=28421656
[INFO] [05-22|02:58:18.958] [2/15 Headers] No block headers to write in this log period block number=28421656
[INFO] [05-22|02:58:38.958] [2/15 Headers] No block headers to write in this log period block number=28421656
[INFO] [05-22|02:58:58.905] [txpool] stat                            pending=1 baseFee=0 queued=14 alloc=2.5GB sys=3.3GB
[INFO] [05-22|02:58:58.958] [2/15 Headers] No block headers to write in this log period block number=28421656
[INFO] [05-22|02:59:18.958] [2/15 Headers] No block headers to write in this log period block number=28421656

**Comment by calmbeing** [comment]
Because you specified prune flag which will prune the data before latest 90000 block, `prune=htc --prune.h.older=90000 --prune.t.older=90000 --prune.c.older=90000 `

**Comment by calmbeing** [comment]
By default, the `rpcdaemon` serves data from `localhost:8545`. Try below command
`curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_blockNumber", "params": [], "id":1}' localhost:8545`

**Comment by setunapo** [comment]
can not reproduce, close
