### ISSUE TITLE
No block headers to write in this log period block number=957

### ISSUE THREAD

**Issue by sepine** [node-real/bsc-erigon#97]
When I synchronized the bsc chain, it was stuck in this position:

![image](https://github.com/node-real/bsc-erigon/assets/28748734/af31f2fe-a4d7-4665-b931-caaa7e7c92b7)

The command I used is ./build/bin/erigon --chain bsc --sentry.drop-useless-peers --datadir /media/Disk/chain/bsc/chaindata --torrent.download.rate=20mb --http.api=eth,erigon,web3,net,debug,trace,txpool --rpc.batch.concurrency 10

The version I used is v1.0.8.

I also try to remove the flag --sentry.drop-useless-peers, but it got the same issue.

**Comment by latifrons** [comment]
Same problem at 957.

**Comment by sepine** [comment]
Any solution about this issue?

**Comment by blxdyx** [comment]
checking

**Comment by setunapo** [comment]
similar issue, close this one.
follow in: https://github.com/node-real/bsc-erigon/issues/94
